### ISSUE TITLE
Add algorithms to check if strings are palindromes?

### ISSUE THREAD

**Issue by arnavb** [OpenGenus/cosmos#1033]
Can I do this in Python and C++? I will place it in a new folder called `palindrome` in the string algorithms section. I plan on doing it in two ways, either by checking equality with the reverse of a string, by recursion, or by a loop.

**Comment by amitsin6h** [comment]
#1042 Implemented using python

**Comment by amitsin6h** [comment]
@AdiChat are you merging my PR or should I close it because @arnavb has also done it with python but his solution is contains lots of code. let me know regarding this

**Comment by amitsin6h** [comment]
@AdiChat #1042 also added JavaScript solution. please review and merge it

**Comment by arnavb** [comment]
@amitsin6h I actually have **3** python solutions in one file. One of my solutions is only 3 lines of code.

**Comment by amitsin6h** [comment]
@arnavb yeah bro thats awesome. 👍 . Thanks for the info i wrnt for sleep now I will update it at morning. Thanks again

**Comment by amitsin6h** [comment]
#1042 merge it

**Comment by AdiChat** [comment]
merged 👍

**Comment by FrankKair** [comment]
Just opened a PR for a Ruby implementation (#1126)

**Comment by tanmaydarmorha** [comment]
Can i do this in Java?

**Comment by AdiChat** [comment]
Sure 👍

**Comment by FrankKair** [comment]
Just opened a PR for a Rust implementation (#1243)

**Comment by AdiChat** [comment]
Sure @varishtsg Go for it 👍
