### ISSUE TITLE
There are two implementation of heap sort in JavaScript

### ISSUE THREAD

**Issue by 948080952** [OpenGenus/cosmos#1065]
They are [heap_sort.js](https://github.com/OpenGenus/cosmos/blob/master/code/sorting/heap_sort/heap_sort.js) and [heapSort.js](https://github.com/OpenGenus/cosmos/blob/master/code/sorting/heap_sort/heapSort.js)

**Comment by arnavb** [comment]
I created a PR for this (PR #1107)
