### ISSUE TITLE
Inconsistent "Case" of names of different sections.

### ISSUE THREAD

**Issue by kapillamba4** [OpenGenus/cosmos#1083]
Example: graph-algorithms is spinal case while computational_geometry is snake Case.

**Comment by arnavb** [comment]
This is the kind of problem that comes up when there is no coding standard. (Yet)

**Comment by kapillamba4** [comment]
Maybe we can just add a link to the google style guide.

**Comment by arnavb** [comment]
@kapillamba4 That's a pretty good idea, but it is just _one_ possibility. Right now, someone has to be willing to actually go and refactor _every_ single file so it conforms to the style guide. A bigger problem than this right now is the actual organization of this project, which is inconsistent.

**Comment by kapillamba4** [comment]
@arnavb The bigger problem is people copy pasting code from geeksforgeeks (and some other sites) which has alot of poorly written code.

**Comment by arnavb** [comment]
@kapillamba4 Their code is not poorly written, it's just that they have their own style.

**Comment by kapillamba4** [comment]
@arnavb yes and @AdiChat i have an idea which can help improve code quality, can you integrate this project with travis ci?

**Comment by arnavb** [comment]
I see what you are trying to say @kapillamba4, but what would a "build" for this repo be?

**Comment by kapillamba4** [comment]
@arnavb @AdiChat  I believe we can use code linters and google style checking "scripts" for different languages for continuous integration. Although i don't have time to search for those on the web and I don't know if travis ci supports such a thing.

**Comment by arnavb** [comment]
Travis CI does support this, but it is a **build system**.

**Comment by AdiChat** [comment]
We have a naming convention in the Contributing guideline wiki which very few contributors have complied to. 

We have impose simple rules in the guidelines which are not so important but it has been seen that contributors had difficulty adjusting to it. In such a scenario, coding guidelines will only discourage contributions. For instance, even @kapillamba4's code does not comply to present guidelines. 

As I already mentioned to others previously, guidelines impose restrictions which discourage almost all contributors which is detrimental for our community.

Ensuring code quality is certainly on our future roadmap and when considering copying code, it is difficult to track down the source of a code to  a person. This is another restriction which cannot be checked. Despite that, we have some quality contributions and contributors. ❤️ 

> This has come far away negatively from the vision.
 
I hope you will corporate in keeping the community intact 👍
