### ISSUE TITLE
Create hashtable in any language

### ISSUE THREAD

**Issue by tbhaxor** [OpenGenus/cosmos#1122]
creating file hashtable.cs in **/code/data_structures/hash_table**

**Comment by tbhaxor** [comment]
@AdiChat thanks bro 👍

**Comment by vedhasp** [comment]
I'll do it :)

**Comment by bitbrain-za** [comment]
Added one in c

**Comment by 948080952** [comment]
I'll do Objective-C and Swift part

**Comment by tbhaxor** [comment]
i am doing in PHP

**Comment by hnrytrn** [comment]
Hey, can I add a Python implementation?
