### ISSUE TITLE
How about listing out Python built-in functions and classes? With a small usage example

### ISSUE THREAD

**Issue by junaid1460** [OpenGenus/cosmos#1136]
I think people should know about Python's built-in modules which are helpful. What about this?

**Comment by karanchawla** [comment]
IMO the documentation does a really good job at that.

**Comment by AdiChat** [comment]
Most of the documentations are available **offline** in the form of docsets. In installation guidelines, we will point to them 👍

**Comment by junaid1460** [comment]
Okay fine
