### ISSUE TITLE
create reverse_stack in any language

### ISSUE THREAD

**Issue by tbhaxor** [OpenGenus/cosmos#1169]
I have created **reverse_stack.php** in _/code/data_structures/stack/reverse_stack_

**Comment by tbhaxor** [comment]
@AdiChat  some pulls are [here](https://github.com/OpenGenus/cosmos/pull/1165)

**Comment by tbhaxor** [comment]
@AdiChat bro i am going to make reverse stack in c

**Comment by Z-Fikar** [comment]
I tried to create it in Java.

@AdiChat would you be kind to review my PR #1206 , please.

**Comment by sgrG24** [comment]
i will implement it in cpp
