### ISSUE TITLE
Request to add my project to your Readme

### ISSUE THREAD

**Issue by itaditya** [OpenGenus/cosmos#1210]
Hey ! I really liked this project and thus wanted to contribute to it. I noticed that you have intended the project to serve as an offline dictionary.
However the project has quickly evolved and the algorithms range has expanded. Due to this finding of algorithms becomes tedious for a user.
To remedy this I have made an online interface for cosmos.
Code - https://github.com/itaditya/cosmos-web-interface
Website - https://cosmos-web.surge.sh/algorithm/bit-manipulation/bit_division

The web interface aims to cater to a larger audience who doesn't necessarily know how to use git/github. 

My project is currently in development but the major features are ready. Also I have designed as such that as new algorithms are added to your repo, the web interface can be updated as well with just one command.

It would be awesome if you could mention my project in your README so that more people can discover this tool.
Thanks

**Comment by AdiChat** [comment]
We have a realtime search tool in progress in which some of our contributors are working. Your interface is good but quite far from what we are looking for. We believe it can be evolved.

Join [Slack](http://slack.opengenus.org/) and get in touch 👍

**Comment by itaditya** [comment]
Ok great
