### ISSUE TITLE
Queue in Javascript

### ISSUE THREAD

**Issue by agrim123** [OpenGenus/cosmos#1222]

**Comment by mlodato517** [comment]
Hello! I'm relatively new to GitHub and was wondering if I could give this one a shot!

**Comment by agrim123** [comment]
@mlodato517 I have already submitted pull request for this issue #1223

**Comment by SarasArya** [comment]
I too have submitted a PR implementation [#1232]( https://github.com/OpenGenus/cosmos/pull/1232)
