### ISSUE TITLE
Adding a majority element algoritm

### ISSUE THREAD

**Issue by andreigasparovici** [OpenGenus/cosmos#1302]

**Comment by andreigasparovici** [comment]
Code: [#1304](https://github.com/OpenGenus/cosmos/pull/1304)

**Comment by ayushkalani** [comment]
I'm interested in doing it, please share the details.

**Comment by andreigasparovici** [comment]
I already did it. See [Pull request #1304](https://github.com/OpenGenus/cosmos/pull/1304)
