### ISSUE TITLE
create lapindrome_checker in any language

### ISSUE THREAD

**Issue by tbhaxor** [OpenGenus/cosmos#1318]
i am creating lapindrome checker in **code/string-algorithms/** in any language

_Lapindrome is defined as a string which when split in the middle, gives two halves having the same characters and same frequency of each character. If there are odd number of characters in the string, we ignore the middle character and check for lapindrome. ... Given a string, you need to tell if it is a lapindrome_

@AdiChat  plz will u make README.md for me ?

**Comment by tbhaxor** [comment]
i am creating in _cpp_ and _python_ and _php_

**Comment by AdiChat** [comment]
Sure 👍

**Comment by tbhaxor** [comment]
@AdiChat  i have added _cpp_ of the same

**Comment by tbhaxor** [comment]
@AdiChat _PHP_ version is also added

kindly check and merge all these

**Comment by IgorAntun** [comment]
Just sent an improvement of the current JS version :)
#1331

**Comment by tbhaxor** [comment]
@AdiChat  created same in python too

kindly merge them :D

**Comment by candalo** [comment]
I have added a palindrome checker implementation in Clojure 
#1413

**Comment by Rishabh570** [comment]
i can do it in c...working on it.

**Comment by AdiChat** [comment]
@Rishabh570 You need to create a folder `lapindrome` under _code/string-algorithms/_ and place your code there 👍

**Comment by suve** [comment]
Sorry to burst in uninvited, but it's "palindrome", not "lapindrome".

**Comment by AdiChat** [comment]
@suve You are always invited 😄 

It is `lapindrome`. We do have a section for `palindrome` under `string-algorithms` as well 👍 

Lapindrome is a string which when split in the middle, gives two halves having the same characters and same frequency of each character. If there are odd number of characters in the string, we ignore the middle character 👍
