### ISSUE TITLE
java code for "FindingSquare" alogrithm incorrect

### ISSUE THREAD

**Issue by gummaph** [OpenGenus/cosmos#1391]
since the variable 'i' that is used in =the for loop has integer data type; values like 5 is being treated as Perfect square(Incorrect behaviour).
 
'i' needs to be float

Also you have unused variables.

**Comment by dusty-wil** [comment]
Can I look at this?

**Comment by dusty-wil** [comment]
@gummaph @AdiChat and, can I add a python version?

**Comment by AdiChat** [comment]
Sure @dusty-wil Go for it 👍

**Comment by dusty-wil** [comment]
@AdiChat Thanks! Just created the PR. It looks like someone already made a python version, so I won't attempt to duplicate their effort.

**Comment by gummaph** [comment]
closing issue. thanks.
