### ISSUE TITLE
Issue and Pull request template

### ISSUE THREAD

**Issue by divyam3897** [OpenGenus/cosmos#1403]
I couldn't find an Issue and Pull request template in .github, it can make the issues and Pull requests more organized?

**Comment by divyam3897** [comment]
I can add them following https://github.com/blog/2111-issue-and-pull-request-templates

**Comment by AdiChat** [comment]
Sure @divyam3897 Go ahead and add one 👍

**Comment by prashant0598** [comment]
@divyam3897 in pull request template u can add  a checklist whether the code is properly commented and also whether the branch is up-to-date or not with master branch.
