### ISSUE TITLE
Add implementation for Inversion count in any language

### ISSUE THREAD

**Issue by faiyaz26** [OpenGenus/cosmos#1430]
Add python implementation for Inversion count problem [here](https://github.com/OpenGenus/cosmos/tree/master/code/divide_conquer/inversion_count)

**Comment by nikw92** [comment]
I'd like to take this.

**Comment by AdiChat** [comment]
Sure @nikw92 Go for it 👍

**Comment by Jiraphapa** [comment]
I've tried adding javascript implementation for Inversion count problem. Apologize if there are any mistakes, this is my very first pull request !

**Comment by edwardrichtofen115** [comment]
Kindly check it's implementation in c.
#2259
