### ISSUE TITLE
There are 2 python files for longest_palindromic_sequence

### ISSUE THREAD

**Issue by sidmishraw** [OpenGenus/cosmos#1439]
`Longest_palindromic_sequence.py` and `longest_palindromic_sequence.py`. Which is the correct one?
![screen shot 2017-10-13 at 6 47 30 pm](https://user-images.githubusercontent.com/16849827/31571409-021b200a-b047-11e7-9a48-6ddb9da0bf0b.png)

- Sid

**Comment by sidmishraw** [comment]
Well, these files sure did a number on my fork😞 

I'll wait for your merge then.

**Comment by Vitorvgc** [comment]
I think that the `longest_palindromic_sequence.py` is also more enhanced, as it uses only O(n) space instead of the other implementation that uses O(n^2).

**Comment by AdiChat** [comment]
Yes, it is 👍 
I have fixed it 👍

**Comment by sidmishraw** [comment]
Fixed my fork, thanks 👍
