### ISSUE TITLE
add bloom-filter implementation in various languages

### ISSUE THREAD

**Issue by abhishekjiitr** [OpenGenus/cosmos#1541]
would like to add bloom filter code in **_data_structures/bloom-filter_**

**Comment by abhishekjiitr** [comment]
@AdiChat

**Comment by AdiChat** [comment]
Sure. Go for it 👍

**Comment by abhishekjiitr** [comment]
#1762 python implementation done!

**Comment by abhishekjiitr** [comment]
I see bloom filter code added in most languages now, Closing the issue! :heavy_check_mark:
