### ISSUE TITLE
Adding max sub matrix sum 

### ISSUE THREAD

**Issue by karanchawla** [OpenGenus/cosmos#1562]
Hey I'd like to add maximum sub matrix sum in the a matrix to the repo? Basically use Kadane's algorithm for each column to find the coordinates of the sub matrix.

**Comment by beingadityak** [comment]
Can I know where's the source file to be kept for this problem? I'm coding the solution in Java

**Comment by AdiChat** [comment]
@beingadityak You need to create a new directory named `maximum_sub_matrix_sum` under `dynamic_programming` 👍

**Comment by beingadityak** [comment]
Please refer PR #1624
