### ISSUE TITLE
Issue & PR template

### ISSUE THREAD

**Issue by prashant0598** [OpenGenus/cosmos#1634]
@AdiChat I was thinking that as our community is growing it is better to have an issue and PR template for new contributors.

**Comment by AdiChat** [comment]
Yes, we need one and we have [a pull request](https://github.com/OpenGenus/cosmos/pull/1419) for this. You can help to make it more central to _Cosmos_ 👍

**Comment by divyam3897** [comment]
there is already an issue for this https://github.com/OpenGenus/cosmos/issues/1403 , so this can be closed.
