### ISSUE TITLE
Add some advanced data structures 

### ISSUE THREAD

**Issue by abhishekjiitr** [OpenGenus/cosmos#172]
I would like to add some advanced data structures like **Binary Indexed Trees**, **Segment Trees**, **Tries** and more in the _data structures_ folder. Would love to work on this stuff!  #hacktoberfest

**Comment by AdiChat** [comment]
Go for it 👍

**Comment by abhishekjiitr** [comment]
@AdiChat should I create a separate folder for _advanced data structures_ or should i make changes in _data structures_ folder only?

**Comment by AkshGautam** [comment]
fenwick tree in cpp and python added please review PR #177

**Comment by AdiChat** [comment]
@abhishekjiitr Create sub-folders for each type. Like a folder named `fenwick_tree` for code of fenwick tree in various languages. 👍

**Comment by AkshGautam** [comment]
@AdiChat  i have already added fenwick tree in two languages. @abhishekjiitr can add segment tree and other DS.

**Comment by abhishekjiitr** [comment]
let me see, if i can improve the code for fenwick tree / BIT
cheers @AkshGautam

**Comment by AkshGautam** [comment]
wait,i seem to have commited a wrong code for fenwick in cpp,let me recommit

**Comment by AkshGautam** [comment]
@AdiChat  review PR #184

**Comment by foikila** [comment]
I have implemneted an ArrayStack i c++. Not sure if it counts as an Advanced data-structure though... 
See PR #82

**Comment by abhishekjiitr** [comment]
@AdiChat please review!
https://github.com/OpenGenus/cosmos/pull/225

**Comment by taakasj** [comment]
@AdiChat Please review the code for trie search and addition in C++
#388

**Comment by abhishekjiitr** [comment]
since a lot of advanced data structures have been accommodated, shall we close this issue @AdiChat ?

**Comment by coffe2code** [comment]
Can I add code in C++ for AVL trees, Red-Black Trees etc.

**Comment by abhishekjiitr** [comment]
sure, just make sure these things are not done by someone else already!
