### ISSUE TITLE
Add morse code generator.

### ISSUE THREAD

**Issue by vshelke** [OpenGenus/cosmos#1744]
A program which converts input string to morse code.

**Comment by michaelkrone** [comment]
I would like to add this in JavaScript. Where should this be located in the folder structure?

**Comment by AdiChat** [comment]
@michaelkrone The code shall be placed at `code/cryptography/morse_cipher/` 👍

**Comment by d3vil0p3r** [comment]
Adding one in C/C++ to the same folder `code/cryptography/morse_cipher/` 👍

**Comment by d3vil0p3r** [comment]
Implementing this in C/C++ to the same folder `code/cryptography/morse_cipher/` 👍

**Comment by eukaryote31** [comment]
I'm implementing this in brainfsck.

**Comment by ckylee** [comment]
I will implement in java (again) x)

**Comment by d3vil0p3r** [comment]
Thanks @sgrG24 for implementation in C++. Going to implement this in Lua now 👍

**Comment by d3vil0p3r** [comment]
@AdiChat #2111

**Comment by eukaryote31** [comment]
Is it okay if I only implement a generator for brainfsck?
