### ISSUE TITLE
Add the median of medians algorithm

### ISSUE THREAD

**Issue by abdouskamel** [OpenGenus/cosmos#1769]
Hello everybody, i'm new here and i'd like to give a small contribution to this project. 
I noticed that there's no code for the median of medians algorithm, a deterministic algorithm for selecting with linear complexity. I wrote it, and i'd be glad to add it to the project. So i'm asking you if that algorithm would be helpful.

Thanks for reading (sorry for bad english).

**Comment by AdiChat** [comment]
Sure @abdouskamel Go and add it 👍

**Comment by abdouskamel** [comment]
Thank you, so i'll create a folder in selection-algorithms ?

**Comment by abdouskamel** [comment]
Thank you, i've made a pull request.

**Comment by Agnishom** [comment]
I implemented this in Python and Haskell. Sent two pull requests.

**Comment by abdouskamel** [comment]
Good job !
