### ISSUE TITLE
Design Patterns

### ISSUE THREAD

**Issue by lamar-frankie** [OpenGenus/cosmos#1774]
Hi, I'm Frank. I really like this project and I want to contribute. Would you consider adding a section for Design Patterns?

**Comment by AdiChat** [comment]
Yes. Design patterns are certainly important and we would love to have a section dedicated to it 👍

**Comment by warlockz** [comment]
Adding design pattern section will be fixed with issue #2217

**Comment by warlockz** [comment]
Please close this issue
