### ISSUE TITLE
create fcfs in any language

### ISSUE THREAD

**Issue by tbhaxor** [OpenGenus/cosmos#1788]
create code fof FCFS (first come first serve) algo in any language at **code/operating_system/first_come_first_serve**

@AdiChat  bro i am adding in `python3` and `csharp` in branch _OS_fcfs_

## What is FCFS?
_The first come, first served (commonly called FIFO ‒ first in, first out) process scheduling algorithm is the simplest process scheduling algorithm. It is rarely used in modern operating systems, but is sometimes used inside of other scheduling systems._

**Comment by Abhishek2019** [comment]
is it fine if i provide java code for FCFS (First in First Out)?

**Comment by tbhaxor** [comment]
I have a request plz include a function of printing gantt chart like i have modified in my PR 1903

**Comment by Abhishek2019** [comment]
ya sure
i will change my java code and create pull again.
Thanks for suggestion

**Comment by dowoncha** [comment]
I put in a request for this in Rust
