### ISSUE TITLE
Code of Conduct

### ISSUE THREAD

**Issue by arnavb** [OpenGenus/cosmos#1804]
**This is a(n)...**

- [ ] New algorithm
- [ ] Update to an existing algorithm
- [ ] Error
- [x] Proposal

**Details:**

According to [Github](https://github.com/OpenGenus/cosmos/community), this repository is not yet at community standards since we do not have a code of conduct. Should we add one?

**Comment by AdiChat** [comment]
Yes. We must add it 👍

**Comment by arnavb** [comment]
But what kind? There are currently two, one for any size project, another for large size ones. You can look them over on the link I posted.

**Comment by prashant0598** [comment]
@arnavb Go with Contributor Covenant

**Comment by arnavb** [comment]
#1839
