### ISSUE TITLE
Unify folders’ and files’ name

### ISSUE THREAD

**Issue by iattempt** [OpenGenus/cosmos#1861]
**This is a(n):**

- [ ] New algorithm
- [x] Update to an existing algorithm
- [ ] Error
- [ ] Proposal to the Repository

**Details:**

unify folders and files name.
please also check that the folders or files has been **include/import,etc.**

if you done same thing, please refer the pull request to this issue

**Comment by iattempt** [comment]
please use sensitive OS to rename [.scala file in this folder](https://github.com/OpenGenus/cosmos/tree/master/code/mathematical-algorithms/factorial) 

thanks😀

**Comment by Vitorvgc** [comment]
For such cases, I find [git mv](https://git-scm.com/docs/git-mv) quite useful to solve these problems.

**Comment by iattempt** [comment]
@Vitorvgc
thank for comment,

I'd try this "git mv" command to move files,
and it seems only works on "only one file" to change case,

but there is two files what with two case version in same directory,
then I can't using this method to fix it.
