### ISSUE TITLE
add Check_is_square in any language

### ISSUE THREAD

**Issue by tbhaxor** [OpenGenus/cosmos#1927]
i am adding check_is_square in `php` and `csharp`

**Comment by blockloop** [comment]
I'll try for C#

**Comment by tbhaxor** [comment]
@blockloop i have commited now bro

**Comment by blockloop** [comment]
Sorry. I misread the opened PR. Thought you were requesting it to be done. :)

**Comment by AdiChat** [comment]
@blockloop Kindly take a look at other scopes of contribution. We have plenty 😄

**Comment by lordozb** [comment]
Can I add in python and Java?

**Comment by AdiChat** [comment]
Sure @lordozb Go for it 👍

**Comment by kakshay21** [comment]
Can I add in Swift?

**Comment by lordozb** [comment]
@AdiChat Fixed the code for Java

**Comment by AdiChat** [comment]
Sure @kakshay21 Go for it 👍

**Comment by teleginzhenya** [comment]
Can I make it with JavaScript?

**Comment by AdiChat** [comment]
Sure @teleginzhenya Go for it 👍

**Comment by edwardrichtofen115** [comment]
I'M doing this in c++
