### ISSUE TITLE
Adding new folders for new mathematical algorithms.

### ISSUE THREAD

**Issue by CaramelHeaven** [OpenGenus/cosmos#1940]
Can we create some code from interpolation polynomials? Like Lagrange or Newton, + divided differences.

- Divided differences - release. Watch in math.

- Lagrange polynomial - Completed.

-  Newton polynomial - Completed.

**Comment by AdiChat** [comment]
Sure 😄 Go for it 👍 

You might want to add the new directory under `mathematical algorithms` 👍

**Comment by CaramelHeaven** [comment]
Okay. Thank you for you answer.

**Comment by CaramelHeaven** [comment]
The main idea is here. You can create it other way.
