### ISSUE TITLE
There are 2 factorial implementation files for Scala, Factorial.scala and factorial.scala

### ISSUE THREAD

**Issue by sidmishraw** [OpenGenus/cosmos#1943]
**This is a(n):**

- [ ] New algorithm
- [ ] Update to an existing algorithm
- [x] Error
- [x] Proposal to the Repository

**Details:**

There are 2 factorial implementations in Scala namely [Factorial.scala](https://github.com/OpenGenus/cosmos/blob/master/code/mathematical-algorithms/factorial/Factorial.scala) and [factorial.scala](https://github.com/OpenGenus/cosmos/blob/master/code/mathematical-algorithms/factorial/factorial.scala). I believe this is a merge related issue.

**Comment by iattempt** [comment]
refer to #1861

**Comment by iattempt** [comment]
#1942 fixed error

**Comment by sidmishraw** [comment]
Closing issue.
