### ISSUE TITLE
Add Java implementation for a bloom filter

### ISSUE THREAD

**Issue by sidmishraw** [OpenGenus/cosmos#2204]
**This is a(n):**

- [x] New algorithm
- [ ] Update to an existing algorithm
- [ ] Error
- [ ] Proposal to the Repository

**Details:**

Add Java implementation for a bloom filter.

**Comment by abhi-rao** [comment]
Hi, I would like to work on it.

**Comment by sidmishraw** [comment]
I've added the implementation. Refer #2205

Caveats:
* Needs a hash mix, will implement Murmur3 hash function utility soon.

**Comment by sidmishraw** [comment]
Merged with the master, closing issue.
