### ISSUE TITLE
Add Singleton Pattern in C++

### ISSUE THREAD

**Issue by leodevo** [OpenGenus/cosmos#2386]
**This is a(n):**

- [ ] New algorithm
- [ x] Update to an existing algorithm
- [ ] Error
- [ ] Proposal to the Repository

**Details:**
Add singleton Add Singleton pattern in C++

PS : It would probably make more sense to merge it with issue : #2354 Add singleton pattern in C# in order to not open an issue for each language.

**Comment by kevinmmurphy** [comment]
Can I take this one?
