### ISSUE TITLE
Add More Maintainers (With Write Access) to Cosmos

### ISSUE THREAD

**Issue by arnavb** [OpenGenus/cosmos#2611]
**This is a(n):**

- [ ] New algorithm
- [ ] Update to an existing algorithm
- [ ] Error
- [x] Proposal to the Repository

**Details:**
I think that given the amount of PRs and new issues that we are getting in this repository, more people need to be added that have write access and can merge PRs. I am not saying that this is _necessary_, but it will be beneficial in merging PRs and closing issues as fast as possible. Otherwise, it might be too much for just one single person to handle.

**Comment by arnavb** [comment]
@AdiChat, please consider this, and if you agree, then please select some people who will have write access.

**Comment by AdiChat** [comment]
Yes, we need to expand our maintainer :family_man_man_boy_boy:  team and in my opinion, we have a few other contributors who can be great for the position. Initially, I planned to give write access to maintainers after _six months of active participation_.

For recent rough time, I have restricted a lot of freedom we had earlier but hope to restore them soon in a safe way. Moreover, write access is a power which can be misused easily or accidentally. In this light, the above constraint makes sense but I hope to relax this soon in some way. 😄 

Distributing write access to a few other members is necessary for our community to be self-sufficient and I will definitely work on this.
