### ISSUE TITLE
Add factorial in C

### ISSUE THREAD

**Issue by etrexel** [OpenGenus/cosmos#2619]
**This is a(n):**

- [ ] New algorithm
- [x] Update to an existing algorithm
- [ ] Error
- [ ] Proposal to the Repository

**Details:**

**Comment by Gupta-shifali** [comment]
Can I implement this in c++ @AdiChat?

**Comment by pruthiviraj71** [comment]
I added a new algorithm for factorial.

**Comment by GingerDragon7** [comment]
Added Factorial in C using recursion technique #2656

**Comment by swapnilbaluja** [comment]
kindly review #2693
