### ISSUE TITLE
Add topological sort algorithm in python

### ISSUE THREAD

**Issue by parulagg27** [OpenGenus/cosmos#2737]
**This is a(n):**

- [ ] New algorithm
- [x] Update to an existing algorithm
- [ ] Error
- [ ] Proposal to the Repository

**Details:**

Adding topological sort algorithm in python.

**Comment by dianagastrin** [comment]
cool, toposort.py ? this is the file right? :)

**Comment by sggoyal1994** [comment]
Adding Topological sort in python 2.7

Thanks,
Team Bleedcode
