### ISSUE TITLE
Calling classes within a class without the use of headers

### ISSUE THREAD

**Issue by abhi1607IIT** [OpenGenus/cosmos#2798]
**This is a(n):**

- [ ] New algorithm
- [ x] Update to an existing algorithm
- [ ] Error
- [ ] Proposal to the Repository

**Details:**

how can we deal with the problem without the use of headers file . For eg I have to carry a code in any coding contest . So what Can i do to avoid multiple files

**Comment by AdiChat** [comment]
Header files are not required in this case. Just create objects of a particular class type and use it. You can create more than one classes in a file. 
Hope this helps 👍
