### ISSUE TITLE
File name conflict

### ISSUE THREAD

**Issue by HidekiHokuto** [OpenGenus/cosmos#2940]
**This is a(n):**

- [ ] New algorithm
- [ ] Update to an existing algorithm
- [ ] Error
- [x] Proposal to the Repository

**Details:**

Some OSX may be case-insensitive, algorithms have same name in a folder may be replaced.
Like `cosmos/code/search/exponential_search.py` and `cosmos/code/search/Exponential_search.py`

**Comment by arnavb** [comment]
#2941
