### ISSUE TITLE
Integrate Travis CI Support

### ISSUE THREAD

**Issue by tbhaxor** [OpenGenus/cosmos#2997]
**This is a(n):**

- [ ] New algorithm
- [ ] Update to an existing algorithm
- [ ] Error
- [ ] Proposal to the Repository
**Details:**

Travis support helps to built and test our programs for unexpected exit and all

**Comment by arnavb** [comment]
I think there is a PR open for this right now, not sure where...

**Comment by InfiniteCoder** [comment]
@arnavb  I had made a PR a few weeks ago #2423. I got an email regarding Travis been allowed to access this organisation by the owner, but I don't know which repo it has been used for.
