### ISSUE TITLE
Add a Folder for Solutions to Online Programming Challenges

### ISSUE THREAD

**Issue by arnavb** [OpenGenus/cosmos#3019]
**This is a(n):**

- [ ] New algorithm
- [ ] Update to an existing algorithm
- [ ] Error
- [x] Proposal to the Repository

**Details:**

I propose adding a folder called `online_challenges`, with nested folders such as `project_euler`, that hold solutions to their respective programming challenges. These still implement algorithms, and are useful in some cases.
I feel this might go against the goals of Cosmos (algorithms), but still might be somewhat related.

**Comment by arnavb** [comment]
@AdiChat, could you consider this?

**Comment by AdiChat** [comment]
This will be a great addition.

Most often, people would like to love to solve challenges which inherently includes learning in the process. That  being said, without network connectivity, one cannot accessible such resources, so, we must solve this problem.

In the case of Project euler and other sites as well, tutorials/ discussions are accessible to people who solves the problem. Thus, this addition will be helpful in a general scenario as well.

An addition should include the problem description in the `readme.md` (including a link to the original problem) as well as the solution code in preferred language. The problem description is required to keep the external dependency as minimal as possible)

**Comment by arnavb** [comment]
Ok, I will do this now.
