### ISSUE TITLE
add subtraction using bit wise operations in any language

### ISSUE THREAD

**Issue by tbhaxor** [OpenGenus/cosmos#3031]
**This is a(n):**

- [x] New algorithm
- [ ] Update to an existing algorithm
- [ ] Error
- [ ] Proposal to the Repository

**Details:**
Add program for subtraction of two numbers using
+ one's complement
+ two's complement

**Comment by sgrG24** [comment]
I will do this in c++.

**Comment by tbhaxor** [comment]
@sgrG24 go for it 👍
