### ISSUE TITLE
add Fibonacci  search in any language

### ISSUE THREAD

**Issue by tbhaxor** [OpenGenus/cosmos#3048]
**This is a(n):**

- [x] New algorithm
- [ ] Update to an existing algorithm
- [ ] Error
- [ ] Proposal to the Repository

**Details:**
check [this](http://www.geeksforgeeks.org/fibonacci-search/)

ps : Don't copy paste the code

**Comment by tbhaxor** [comment]
i can add in `cpp` or `python`

**Comment by erwolfe** [comment]
I will do this in swift!

**Comment by iattempt** [comment]
I'll try this in c++~

**Comment by iattempt** [comment]
#3059 @erwolfe

**Comment by nipunbharti** [comment]
I'll try this in JS

**Comment by nipunbharti** [comment]
I have implemented this in C
