### ISSUE TITLE
add highlight message for PR

### ISSUE THREAD

**Issue by iattempt** [OpenGenus/cosmos#3055]
**This is a(n):**
- [ ] New algorithm
- [ ] Update to an existing algorithm
- [ ] Error
- [x] Proposal to the Repository

**Details:**
please add to pull request message:
"Make sure code or file is existed"
and
"if file name is same (e.g., Search.cpp and  search.cpp), and really want remain two files, then rename a file to search2.cpp"

the name conflicts is common issue.

**Comment by arnavb** [comment]
You could do this @iattempt, it is just two sentences to the PR template.

**Comment by iattempt** [comment]
I know it, but my english is not good...

**Comment by iattempt** [comment]
Fixed
