### ISSUE TITLE
add solutions of code chef in code/online_challenges/

### ISSUE THREAD

**Issue by tbhaxor** [OpenGenus/cosmos#3074]
**This is a(n):**

- [ ] New algorithm
- [ ] Update to an existing algorithm
- [ ] Error
- [x] Proposal to the Repository

**Details:**

I have created some solution for some codechef problems check [this](https://github.com/OpenGenus/cosmos/pull/3062)
**Note** : not all problems are working fine, but most of them are working. 

I would like you to add some working solution to the problems of codechef

# Format To Follow
1. Add Solutions to the directory named after difficulty level
+ Beginner
+ Easy
... and so on
2. Add file with the name like `<problem_code>.<ext>`

**Comment by tbhaxor** [comment]
@AdiChat @arnavb

**Comment by AdiChat** [comment]
This will be great. Go for it 👍

**Comment by tbhaxor** [comment]
@adichat have u chkd my REPO ?
