### ISSUE TITLE
make it available on web

### ISSUE THREAD

**Issue by frtug** [OpenGenus/cosmos#3081]
it should be present

**Comment by arnavb** [comment]
What is "it"?

**Comment by engrravijain** [comment]
are you trying to say that we should have a website for cosmos ?

**Comment by arnavb** [comment]
Isn't this a website (😆)

**Comment by tbhaxor** [comment]
@arnavb @AdiChat 
After my exams i will make a website implementing all cosmos algos :smile:

**Comment by frtug** [comment]
Sorry to bother you i was just testing the feature button

**Comment by arnavb** [comment]
What feature button? 😕

**Comment by frtug** [comment]
comment

**Comment by arnavb** [comment]
ok...

**Comment by arnavb** [comment]
@AdiChat could you please close this issue as it really isn't of any benefit to anyone.

**Comment by AdiChat** [comment]
Sure :+1:

**Comment by tbhaxor** [comment]
@adichat i am developing a web app which which contains the implementation of all the algos included in cosmos

**Comment by tbhaxor** [comment]
@arnavb @AdiChat  i need some `HTML` and `CSS` developer for my web app...
Will you help me ?

**Comment by arnavb** [comment]
Doesn't our search engine already contain all the algorithms? What exactly is the goal of this website @tbhaxor. Anyways, I would love to contribute if @AdiChat approves. You could even add the repository to the OpenGenus organization!

**Comment by tbhaxor** [comment]
@arnavb  my idea is concerned with implementing all your algorithms
Features that will be included in my idea
1. Explaining Algorithms with Images
2. Generating Answers on user input
