### ISSUE TITLE
Can we force separation of test file and sources?

### ISSUE THREAD

**Issue by iattempt** [OpenGenus/cosmos#3107]
**This is a(n):**

- [ ] New algorithm
- [ ] Update to an existing algorithm
- [ ] Error
- [x] Proposal to the Repository

**Details:**

Since this project is a lib, one can use source code to create his / her code, but these files do not include the necessary code, but also the test code and the header files it uses, but one may not want these .

**Comment by AdiChat** [comment]
This will be a nice addition.
It is important to enable users to extend/ use the source code in Cosmos to develop their version. Separation of test and source code will refine the structure but we must, also, consider easy access for a user. 

What structure are you considering for this?

**Comment by iattempt** [comment]
Refer to these projects:


- [googletest](https://github.com/google/googletest/tree/master/googletest)
  - [src](https://github.com/google/googletest/tree/master/googletest/src)
  - [test](https://github.com/google/googletest/tree/master/googletest/test)

- [opencv](https://github.com/opencv/opencv/tree/master)
  - [modules](https://github.com/opencv/opencv/tree/master/modules)
    - [core](https://github.com/opencv/opencv/tree/master/modules/core)
        - [src](https://github.com/opencv/opencv/tree/master/modules/core/src)
      - [test](https://github.com/opencv/opencv/tree/master/modules/core/test)
  - [cudaarithm](https://github.com/opencv/opencv/tree/master/modules/cudaarithm)
    - [src](https://github.com/opencv/opencv/tree/master/modules/cudaarithm/src)
    - [test](https://github.com/opencv/opencv/tree/master/modules/cudaarithm/test)

It seems like the best idea to separate the "src" and "test" to each category in code folder:

- [code](https://github.com/OpenGenus/cosmos/tree/master/code)
  - [artificial_intelligence](https://github.com/OpenGenus/cosmos/tree/master/code/artificial_intelligence)
    - [linear_regression](https://github.com/OpenGenus/cosmos/tree/master/code/artificial_intelligence/Linear_Regression)
      - [src]
        - [linear_regression.js]
        - [linear_regression.py]
      - [test]
        - [linear_regression.js]
        - [linear_regression.py]

In addition, the output of sorting algorithms is same, we can do this:
- [code](https://github.com/OpenGenus/cosmos/tree/master/code)
  - [sorting](https://github.com/OpenGenus/cosmos/tree/master/code/sorting)
    - [src]
      - [quick_sort]
        - [quick_sort.py]
        - [quick_sort.java]
      - [merge_sort]
        - [merge_sort.cpp]
    - [test]
      - [sort.py]
      - [sort.java]

**Comment by iattempt** [comment]
@arnavb Do you have any idea?

**Comment by arnavb** [comment]
@iattempt, I personally like the last recommendation that you made, with each category having a src and test folder. I think that is the approach that should be taken.

**Comment by AdiChat** [comment]
Yes, this structure will be better to support test files which is necessary. :+1:

**Comment by iattempt** [comment]
Ok, I will do this recently.

**Comment by iattempt** [comment]
Solved.
