### ISSUE TITLE
Add Palindome.py and palindrome_substring.py

### ISSUE THREAD

**Issue by engrravijain** [OpenGenus/cosmos#3113]
**This is a(n):**

- [x ] New algorithm
- [ ] Update to an existing algorithm
- [ ] Error
- [ ] Proposal to the Repository

**Details:**
These two programs are for finding weather a string is a palindrome or not while the other finds all the sub strings of a given string that are palindrome

to be added in utility/palindrome

**Comment by iattempt** [comment]
The first file existed in string_algorithms, I moved into utility in P.R. above.
