### ISSUE TITLE
[Travis-CI] libgraph-1.0.2 generates compilation errors

### ISSUE THREAD

**Issue by abdouskamel** [OpenGenus/cosmos#3221]
**This is a(n):**

- [ ] New algorithm
- [ ] Update to an existing algorithm
- [x] Error
- [ ] Proposal to the Repository

**Details:**

Hello everybody,

I noticed that libgraph-1.0.2 generates compilation errors in Travis-CI C build. Errors are of the type : 

> use of undeclared identifier 'FONTDIR'

You can check the build [here](https://travis-ci.org/OpenGenus/cosmos/jobs/331927941). Maybe the person who added this library can check to fix this ?

**Comment by willnode** [comment]
Yeah libgraph is in travis.yml but I haven't sure why it's there.

Anyway why we use tests in first place? It's seems only configured for C++ only.

**Comment by InfiniteCoder** [comment]
@willnode Its work in progress. Build and test checks have to be applied to other languages as well.

**Comment by Mithilan16** [comment]
@willnode  I'am aware of the FONT DIR error and have been looking for a solution but libgraph is required to compile a couple files in the cellular_automation directory

**Comment by InfiniteCoder** [comment]
@Mithilan16 This library hasn't been updated for almost 12 years now. Also, it tries to implement Turbo C graphics features on Linux. Given how much things have changed in Linux in last decade, I think probably it's an issue with one of the dependency getting updated. 
I think it's just better to use OpenGL instead. Maybe these programs should be removed.

**Comment by Mithilan16** [comment]
@InfiniteCoder I can take care of that.This means that I will have to remove any program that requires SDL and graphics.h

**Comment by InfiniteCoder** [comment]
@Mithilan16 Yes, and if and when you do that, also remove that library and all it's dependencies from travis.yml 👍

**Comment by abdouskamel** [comment]
Does SDL depends on libgraph ?

**Comment by InfiniteCoder** [comment]
@abdouskamel Thanks for noting that! SDL is independent of libgraph, they have no relation. @Mithilan16 You wouldn't have to remove SDL based programs.

**Comment by abdouskamel** [comment]
@thatguy227 You should mention this issue in your pull request.

**Comment by arnavb** [comment]
@abdouskamel Has this issue been resolved to your knowledge? I opened a new PR for this. #3311 I am going to close it now, since this already exists.

**Comment by arnavb** [comment]
@abdouskamel Update! I have opened #3363 which fixes this issue!

**Comment by abdouskamel** [comment]
@arnavb No, this issue hasn't been resolved yet. Thank you for your pull request.

**Comment by abdouskamel** [comment]
@arnavb I guess I can close it now ?

**Comment by arnavb** [comment]
@abdouskamel Yes, I would close it, as libgraph is no longer a problem for the c build.
