### ISSUE TITLE
Guidelines link is not directing to right page

### ISSUE THREAD

**Issue by SnehaR26** [OpenGenus/cosmos#3250]
**This is a(n):**

- [ ] New algorithm
- [ ] Update to an existing algorithm
- [x] Error
- [ ] Proposal to the Repository

**Details:**

When one tries to create the first Pull request, One gets the message

 **'First time contributing to open genus/cosmos? 
If you know how to fix an issue, consider opening a pull request for it.
You can read this repository’s contributing guidelines to learn how to open a good pull request.**  

The _contributing Guidelines_ page is not directing me to the required page. Instead it directs to the contributors page. Same thing happens when I tried to write an issue and as always there was a help box which reads 
**Before you open an issue please review the contributing and conduct guidelines for this repository.**
When I click on _contributing_, it again directs me to contributors page.

I am not sure whether it is an error or a temporary maintenance issue.    

![save1](https://user-images.githubusercontent.com/32961290/36026582-d05e2588-0dbd-11e8-97a0-9419a71c9dab.JPG)
![save2](https://user-images.githubusercontent.com/32961290/36026590-d90bc41a-0dbd-11e8-8636-6dcbff7a5633.JPG)
![save4](https://user-images.githubusercontent.com/32961290/36026647-0ca37b24-0dbe-11e8-877d-4449e0b7dd09.JPG)

**Comment by SnehaR26** [comment]
PPS Forgive me if there was an error in the above issue, because I obviously couldn't read the guidelines ;-)

**Comment by abdouskamel** [comment]
True, the link sends to contributors list.

**Comment by parulagg27** [comment]
Yeah, facing the same issue.

**Comment by arnavb** [comment]
@SnehaR26  I have opened another issue that actually lists the resolution to this. You may want to take it on by adding a comment to the issue.

**Comment by arnavb** [comment]
@SnehaR26 Please close this issue now, as it is resolved!
