### ISSUE TITLE
No specific format for documentation of various algorithms

### ISSUE THREAD

**Issue by parulagg27** [OpenGenus/cosmos#3261]
**This is a(n):**

- [ ] New algorithm
- [ ] Update to an existing algorithm
- [ ] Error
- [x] Proposal to the Repository

**Details:**

I went through the readme files of various algorithms in this repo & observed that none of them followed a specific format. Some of them only have a definition & an external link for further reading, for ex., [bogo_sort](https://github.com/OpenGenus/cosmos/tree/master/code/sorting/src/bogo_sort) , while others have a proper explanation, for ex., [bubble_sort](https://github.com/OpenGenus/cosmos/tree/master/code/sorting/src/bubble_sort).
 I think, there must be some specific format for creating readme files of these algorithms. For example, for every algorithm, we must give all it's necessary details: i.e., *explanation, pseudcode & time complexity* , while other details are good to have but optional . In the contribution guides folder, there must be documentation guide as well along with coding style guide.
 Since, our end goal is to provide user an offline interface & reduce search time, following a specific format for documentation will definitely improve usability of this project by external applications.

**Comment by parulagg27** [comment]
I propose this template

# Algorithm_Name
Description

## Example/Explanation
Pictorial diagram to explain

## Algorithm
Algorithm in words

## PseudoCode


## Complexity
Time and space complexity

**Comment by parulagg27** [comment]
Update: I've submitted 2 PRs: #3278 & #3280 , as an example of template proposed above for the readme files of each algorithm.
 It would be better, if we can add a documentation guide as well in the contribution guides folder, with this as a template/ specific format for each readme file,  in order to guide new contributors, and thus for improving overall documentation of this repo. Please give your suggestions and reviews. :D

**Comment by AdiChat** [comment]
The documentation format looks good. We may use this as the standard style. 👍 

Documentation is an important part and an extensive coverage with greatly enhance the utility of Cosmos. Feel free to compile the documentation guide using this as the template and send it as a pull request.

**Comment by piyush0033** [comment]
Thanks! Will be working on this issue. 👍

**Comment by parulagg27** [comment]
Thanks! Will be working on this issue👍
