### ISSUE TITLE
Update our Contributing Guidelines so that they are actually contributing guidelines!

### ISSUE THREAD

**Issue by arnavb** [OpenGenus/cosmos#3299]
**This is a(n):**

- [ ] New algorithm
- [ ] Update to an existing algorithm
- [ ] Error
- [x] Proposal to the Repository

**Details:**

- Right now, our [contributing page](https://github.com/OpenGenus/cosmos/blob/master/.github/CONTRIBUTING.md) contains a list of our contributors. While this is fine, it doesn't contain what it is supposed to: contributing guidelines!
- This can be confusing for new users who navigate to this link from the pull request/issue creation link.
- I propose that someone adds a section to the contributing guidelines, right before the contributors' list, that lists our contributing guidelines.

Shoutout to @SnehaR26 for finding this issue in #3250!

Any of our  new (or old) contributors can take this issue on, please add a comment if you want to do so and reference this issue in your PR.

**Comment by SnehaR26** [comment]
Can I take up this issue?

**Comment by arnavb** [comment]
@SnehaR26 Yes you can take this up. Making a separate file is also a good idea, except that you should change the name of the file CONTRIBUTING.md to CONTRIBUTORS.md. Call the new file CONTRIBUTING.md.

**Comment by SnehaR26** [comment]
Sure! 
Is contributing guidelines an amalgamation of code of conduct and style guides for various languages?

**Comment by arnavb** [comment]
Basically the style guide should tell what the user needs to do before contributing, which is

1. Look at the style guides for your language
2. Follow the code of conduct
3. Make sure the algorithm is not already implemented

Obviously, more detail is needed, but this is what I came up with at my first thought.

**Comment by vandana1212** [comment]
@arnavb may I also work on this issue ?

**Comment by arnavb** [comment]
@vandana1212 Well, since @SnehaR26 has already taken up the issue, there really is nothing you can do that I know of. (This is a pretty minor change). I would ask Sneha if there really is anything you can do. 👍
