### ISSUE TITLE
boolean_parenthesization.cpp does not follow coding style guide

### ISSUE THREAD

**Issue by rimshaakhan** [OpenGenus/cosmos#3326]
**This is a(n):**

- [ ] New algorithm
- [x] Update to an existing algorithm
- [ ] Error
- [ ] Proposal to the Repository

**Details:**
There should be spaces  between operator and operands.
Also, avoid using namespaces.

**Comment by arnavb** [comment]
@rimshaakhan Please close this issue as it is now resolved!

**Comment by danos7777** [comment]
Ok I'm closing this
