### ISSUE TITLE
Update links on your website

### ISSUE THREAD

**Issue by tbhaxor** [OpenGenus/cosmos#3369]
**This is a(n):**

- [ ] New algorithm
- [x] Update to an existing algorithm
- [x] Error
- [ ] Proposal to the Repository

**Details:**

This SS will explain every thing

![image](https://user-images.githubusercontent.com/28386721/36973449-0f5c39ee-2099-11e8-9bf1-cdd693c2ad03.png)

**Comment by iattempt** [comment]
Please change links with Cosmos Search
In the situation above:
http://search.opengenus.org/query/?q=fibonacci+search
