### ISSUE TITLE
Need your contribution to a new web app related to Cosmos

### ISSUE THREAD

**Issue by tbhaxor** [OpenGenus/cosmos#3381]
**This is a(n):**

- [ ] New algorithm
- [ ] Update to an existing algorithm
- [ ] Error
- [ ] Proposal to the Repository

**Details:**

I am creating a new web app that is powered by almost all the algorithms coded in cosmos
![image](https://user-images.githubusercontent.com/28386721/37056633-fd0b2e5e-21aa-11e8-8995-b330128017b3.png)

Link to repository : https://github.com/tbhaxor/cos_mos
Web App link : http://tbhaxor.me/cos_mos

Skills Required : JavaScript, HTML, CSS

**Comment by tbhaxor** [comment]
@arnavb my app will work like this
also i will include all the links to your resource 
@AdiChat will u approve it ?

**Comment by arnavb** [comment]
@tbhaxor Have you made pushed any of the changes in your screenshot to your website? I can't seem to find this palindrome link, for example.

**Comment by tbhaxor** [comment]
its on localhost
wait 4 5 secs

**Comment by tbhaxor** [comment]
@arnavb  due to some reason i m unable to push
u can visit this link i am using port forwarding

Link to algo : http://f6df69a2.ngrok.io/cos_mos/algorithms/string/palindrome/

**Comment by tbhaxor** [comment]
@arnavb 
here you go 
http://tbhaxor.me/cos_mos/

click on palindrome

**Comment by tbhaxor** [comment]
@arnavb  
Lipogram tester added
http://tbhaxor.me/cos_mos/

**Comment by arnavb** [comment]
@tbhaxor Hold your horses! Don't just go on adding changes before @AdiChat's approval! This might be a big waste of time if he feels it is not necessary (Or if AdiChat feels it _is_). 🏇

**Comment by tbhaxor** [comment]
@arnavb  i know bro
this is like my TIME PASS Activity :laughing:

**Comment by AdiChat** [comment]
It is not clear what you are trying to achieve. Moreover, we should keep projects developed over Cosmos separate from Cosmos. 

A couple of contributors have developed applications over Cosmos as personal projects and we do encourage it. :+1: 

It seems you are using the `JS` codes but you might not find it for all algorithms and in its current state, it is not providing any unique insights. It looks like a basic testing application. We did receive a similar request a couple of months back. I would like to point out that anyone can initiate a productive idea from within OpenGenus and work on it. We do have some freedom that is safe for everyone. 

It looks like a personal project (as you have indicated above) so, we are not in a position to approve or disapprove it or link it. Personal means a "separate entity". Feel free to continue it if you wish to.
