### ISSUE TITLE
Links mentioned in wiki pages aren't working and a few information is not updated

### ISSUE THREAD

**Issue by parulagg27** [OpenGenus/cosmos#3385]
**This is a(n):**

- [ ] New algorithm
- [ ] Update to an existing algorithm
- [x] Error
- [ ] Proposal to the Repository

**Details:**

I was going through the wiki pages of this repository and observed that:
- In the [home page](https://github.com/OpenGenus/cosmos/wiki):
   1. links of all the algorithms listed there, aren't working
   2. The style guides link, given at the end is also not working
- In the [contribution guidlines page](https://github.com/OpenGenus/cosmos/wiki/contribute) :
   1. Links mentioned for code examples, such as link for **code binary search in Java**, aren't working.
   2. Link to join slack channel isn't working. It should rather direct to [OpenGenus-Slack](https://github.com/OpenGenus/OpenGenus-Slack) repository and ask for creating an issue. Or, according to me, as links for the same are already mentioned in [home page](https://github.com/OpenGenus/cosmos/wiki), so, it can be removed from [contribute page](https://github.com/OpenGenus/cosmos/wiki/contribute)
   3. Template for Readme files isn't updated as per the [new template](https://github.com/OpenGenus/cosmos/blob/master/guides/documentation_guide.md)

Maintainers, please see to it.

**Comment by parulagg27** [comment]
I would like to work on this issue.

**Comment by AdiChat** [comment]
Thanks @parulagg27 for pointing this. I have fixed the links. :+1:

**Comment by parulagg27** [comment]
Oh, great :D . I'm closing this issue.

**Comment by nickdex** [comment]
@AdiChat I just tried to open the Slack link from contribute page it sent me to - [Old link](http://slack.opengenus.org)
I discovered this issue and found the working [slack link](https://opengenus.slack.com) from [OpenGenus-Slack](https://github.com/OpenGenus/OpenGenus-Slack)

I'm creating a PR to fix this
