### ISSUE TITLE
Playing with operations using numbers

### ISSUE THREAD

**Issue by ankita2001** [OpenGenus/cosmos#3414]
**This is a(n):**

- [x ] New algorithm
- [ ] Update to an existing algorithm
- [ ] Error
- [ ] Proposal to the Repository

**Details:**

I want to add various aspects of operations in a number which defines and deliver it in different forms. Operations as if:
1. Prime number or not.
2. Even or odd.
3. Factorial of a number.
4. Converted into number system forms:
A-)  Binary form
B-)  Decimal form
C-)  Hexadecimal form
D-)  Octal form
5. Armstrong of that number.

**Comment by adeen-s** [comment]
We have algorithms to check for all these properties, and conversions. In my opinion, combining all these in a single program will serve no further purpose.

**Comment by arnavb** [comment]
I agree with @adeen-s. These operations already have their own separate implementations. Combining them serves no real purpose.
