### ISSUE TITLE
Missing print statement in queue.py in line 43

### ISSUE THREAD

**Issue by mansiag** [OpenGenus/cosmos#3440]
**This is a(n):**

- [ ] New algorithm
- [x] Update to an existing algorithm
- [ ] Error
- [ ] Proposal to the Repository

**Details:**
Missing print statement in line 43 in [queue.py](https://github.com/OpenGenus/cosmos/blob/master/code/data_structures/src/queue/queue/queue.py).

**Comment by erobynreid** [comment]
I would like to work on this if no one is already working on it.

**Comment by mansiag** [comment]
Yeah, go for it.:smile:

**Comment by erobynreid** [comment]
Should the implementation of queue.py match the queue.c implementation which has an option to print the entire queue as well as enqueue or dequeue and item?

**Comment by mansiag** [comment]
@arnavb Please help here:smile:

**Comment by arnavb** [comment]
@erobynreid No, it isn't necessary, but it would keep a level of consistency (which is lacking right now) between all of the languages. It's really up to you.
