### ISSUE TITLE
prefix_to_postfix.py does not give the required output

### ISSUE THREAD

**Issue by mansiag** [OpenGenus/cosmos#3457]
**This is a(n):**

- [ ] New algorithm
- [ ] Update to an existing algorithm
- [x] Error
- [ ] Proposal to the Repository

**Details:**
[prefix_to_postfix.py](https://github.com/OpenGenus/cosmos/blob/master/code/data_structures/src/) converts an infix expression to postfix expression rather than converting a prefix expression to postfix expression. The algorithm needs to be corrected to give the required output.

**Comment by erobynreid** [comment]
I would like to work on this issue if no one is doing so already.
