### ISSUE TITLE
Updating Insertion sorts documentation to adhere to documentation template

### ISSUE THREAD

**Issue by calemon** [OpenGenus/cosmos#3461]
**This is a(n):**

- [ ] New algorithm
- [x] Update to an existing algorithm
- [ ] Error
- [ ] Proposal to the Repository

**Details:**

Currently in the insertion sort documentation, it lists an overview and the time complexity of the algorithm. It should be updated so that it will follow the [documentation template](https://github.com/OpenGenus/cosmos/wiki/documentation_template) of the repo. I will update it so that it follows the documentation template and gives more information/overview of the algorithm.

**Comment by calemon** [comment]
Pull request at #3462

**Comment by arnavb** [comment]
@calemon Please close this issue!

**Comment by Srashtimittal** [comment]
I am a gssoc 2020 participant. I want to contribute on this issue. Please assign me this issue.
