### ISSUE TITLE
STEINER TREE PYTHON

### ISSUE THREAD

**Issue by brunaostii** [OpenGenus/cosmos#3480]
**This is a(n):**

- [x] New algorithm
- [ ] Update to an existing algorithm
- [ ] Error
- [ ] Proposal to the Repository

**Details:**

Can anybody implements the steiner tree by using python?

**Comment by arnavb** [comment]
@brunaostii If you want to do it, you can. On a side note, could you _not_ use all caps in the title?

**Comment by arnavb** [comment]
@brunaostii Why close?
