### ISSUE TITLE
Affine.java : BUG

### ISSUE THREAD

**Issue by christianbender** [OpenGenus/cosmos#3514]
* The program ```Affine.java``` ([here](https://github.com/OpenGenus/cosmos/blob/master/code/cryptography/src/affine_cipher/Affine.java)) has a bug. The encryption process fails.  I fixed it. Now it run correct.  
```java
 private static void encrypt(int a, int b, String plaintext)
```
The method above has a bug.  

I fixed this issue #3513

**Comment by arnavb** [comment]
@christianbender Make sure that when your PR gets merged, you close this issue as well. Cheers!

**Comment by christianbender** [comment]
@arnavb of course
