### ISSUE TITLE
Fast Matrix Multiplication and Fast Integer Multiplication

### ISSUE THREAD

**Issue by sahitpj** [OpenGenus/cosmos#3587]
**This is a(n):**

- [x] New algorithm
- [ ] Update to an existing algorithm
- [ ] Error
- [ ] Proposal to the Repository

**Details:**

I wish to add the following two algorithms which use the divide and conquer strategy-

1. Fast matrix multiplication - Strassen's Algorithm 
2. Fast Integer multiplication -  Karatsuba Algorithm 

Mathematically it be can be shown that the following algorithms are faster than the normal matrix multiplication and the normal Integer multiplication.

**Comment by DeVasu** [comment]
@sahitpj  Have you yet added those Algorithms? I wish to work on them if you haven't yet

**Comment by sahitpj** [comment]
@DeVasu I have worked on the Python versions and C++ versions of them already. You can work on the others if you wish
