### ISSUE TITLE
Travis fails in case of .C file

### ISSUE THREAD

**Issue by ritwik12** [OpenGenus/cosmos#3594]
**This is a(n):**

- [ ] New algorithm
- [ ] Update to an existing algorithm
- [x] Error
- [ ] Proposal to the Repository

**Details:**

This issue is related to the travis build fail in case of ".c" files which is noticed in PR #3579. I noticed that in travis configuration we are having "make c" which uses make file. In the make file, here we have something like compiling all the ".c" files. See [this](https://github.com/OpenGenus/cosmos/blob/a1580ec20dd10438d07fa6596975eddb42b72ecc/makefile#L3), due to this whenever we have a new PR with ".c" extension it will complile all the ".c" files. And as there are lot many errors in many ".c"  files that the travis build will always fail. I would request to either correct all the files with errors (which will be very hard and time consuming for a single person), correct make file, or correct travis.yml.

**Comment by arnavb** [comment]
@ritwik12 Yes, we are current aware of this, but are working on it slowly. There are other issues open with the same intent as this, so I believe this can be closed.

**Comment by ritwik12** [comment]
@arnavb Sure
