### ISSUE TITLE
The algo. of bubble sort markdown is wrong.

### ISSUE THREAD

**Issue by iattempt** [OpenGenus/cosmos#3844]
**This is a(n):**

- [ ] New algorithm
- [ ] Update to an existing algorithm
- [x] Error
- [ ] Proposal to the Repository

**Details:**

We've left out a for-loop in [this algorithm](https://github.com/OpenGenus/cosmos/blob/master/code/sorting/src/bubble_sort/README.md#algorithm)

**Comment by arnavb** [comment]
You're right @iattempt! Any chance you could go and fix it?

**Comment by AdiChat** [comment]
Thanks @iattempt for spotting and fixing this :+1:
