### ISSUE TITLE
25 Python files use Python 2 or have Syntax Errors

### ISSUE THREAD

**Issue by arnavb** [OpenGenus/cosmos#4002]
**This is a(n):**

- [ ] New algorithm
- [ ] Update to an existing algorithm
- [x] Error
- [ ] Proposal to the Repository

**Details:**

According to our [Travis CI](https://travis-ci.org/OpenGenus/cosmos) builds, 25 files have some sort of error (either usage of Python 2 or syntax errors).

These need to be fixed so that the code works properly. If anyone would like to fix, please comment below!

**Comment by Arunkumar0258** [comment]
I would like to fix them! Can you tell which files?

**Comment by arnavb** [comment]
@Arunkumar0258 Go for it! To find files this is the case for, look at this [build](https://travis-ci.org/OpenGenus/cosmos/jobs/511080512).

**Comment by Arunkumar0258** [comment]
@arnavb How do I change the code? I can't find the file (bipartite.cpp) in master branch. Do I have to copy code, modify it and file a separate PR?

**Comment by arnavb** [comment]
@Arunkumar0258 You're looking at the wrong files. You should be looking at ones highlighted in red following [this line](https://travis-ci.org/OpenGenus/cosmos/jobs/511080512#L468).

**Comment by yedhink** [comment]
@arnavb i will port the strassens multiplication implemented in python2 to python3.
