### ISSUE TITLE
One JS file has a syntax error, and 5+ files need to be reformatted

### ISSUE THREAD

**Issue by arnavb** [OpenGenus/cosmos#4013]
**This is a(n):**

- [ ] New algorithm
- [ ] Update to an existing algorithm
- [x] Error
- [ ] Proposal to the Repository

**Details:**

According to [this build](https://travis-ci.org/OpenGenus/cosmos/jobs/513748786#L454), one JS file has a syntax error and 5+ files need to be reformatted. If anyone would like to fix the syntax error and format the code with [prettier](https://github.com/prettier/prettier), please comment below.

**Comment by arnavb** [comment]
Ok, so the syntax error in `tower_of_hanoi.js` has been fixed. This leaves the formatting the code using prettier. Would anyone like to do this?

**Comment by Arunkumar0258** [comment]
@arnavb I can format the code. Can I work on it?

**Comment by arnavb** [comment]
@Arunkumar0258 Go for it!
