### ISSUE TITLE
Liang Barskey Line Clipping Algorithm 

### ISSUE THREAD

**Issue by robotjellyzone** [OpenGenus/cosmos#4066]
**This is a(n):**

- [x] New algorithm
- [ ] Update to an existing algorithm
- [ ] Error
- [ ] Proposal to the Repository

**Details:**

This algorithm uses a graphics library to clip the lines.

**Comment by msknkh** [comment]
Can i take up this issue?

**Comment by robotjellyzone** [comment]
hi, @msknkh I am working on it (slowly, due to my exams) , you can either take other issues which are up for grabs or make a new issue if you want.
