### ISSUE TITLE
Add Quick Sort

### ISSUE THREAD

**Issue by bureken** [OpenGenus/cosmos#41]
Add the code for bucket sort in any language ( C, C++, Java, Go, Python or any other)

The code should be placed at [code/sorting/quick sort](https://github.com/OpenGenus/cosmos/tree/master/code/sorting/quick_sort)

Note: multiple contributors can work on this issue as it has multiple parts (languages)

Your pull request will be reviewed by maintainers instantly.

For contribution guidelines, see this

If you need any help, let us know.

**Comment by jainkeval** [comment]
I would do it for c and javascript

**Comment by aedorado** [comment]
Adding quicksort for java.

**Comment by endiliey** [comment]
Implementing it in c++

**Comment by jainkeval** [comment]
what do u expect to do in js..
just a function or an html file

**Comment by AdiChat** [comment]
A `JavaScript` function will do.

**Comment by harshit98** [comment]
I will add quicksort in Go language. 👍

**Comment by haggcoder** [comment]
Adding **Quick Sort** in **C#**
