### ISSUE TITLE
Minimum Queue in C++

### ISSUE THREAD

**Issue by tomaz1502** [OpenGenus/cosmos#4107]
**This is a(n):**

- [x] New algorithm
- [ ] Update to an existing algorithm
- [ ] Error
- [ ] Proposal to the Repository

**Details:**

The new data structure is a queue that allows the user to get the minimum element on it in constant time

**Comment by pranaychatterjee** [comment]
Can you please elaborate your issue? I am interested to solve it and make a contribution.

**Comment by tomaz1502** [comment]
Sorry, I've already solved it and made a pull request, just waiting for review. It's here: https://github.com/OpenGenus/cosmos/pull/4108

**Comment by pranaychatterjee** [comment]
Hey Pal ,

It's alright. Tell me if I could help you in any way.

Enjoy the rest of your day.

Regards,
Pranay Chatterjee.
