### ISSUE TITLE
Adding an is_empty() function to stack in python

### ISSUE THREAD

**Issue by yashshah1** [OpenGenus/cosmos#4271]
**This is a(n):**

- [ ] New algorithm
- [x ] Update to an existing algorithm
- [ ] Error
- [ ] Proposal to the Repository

**Details:**
The current implementation of stack in python doesn't have a generic is_empty() function, but calls the same assert condition in both peek() and pop() function.
Hence, there is no abstracted way of determining if the stack is really empty without peeking, or popping.

**Comment by sharontlin** [comment]
I'd like to take on this issue! I'll make a pull request for the change.

**Comment by yashshah1** [comment]
@sharontlin I have already submitted a PR above, referencing this issue
