### ISSUE TITLE
[LeetCode] Add solution to longest substring without repeating characters

### ISSUE THREAD

**Issue by nikochiko** [OpenGenus/cosmos#4348]
**This is a(n):**

- [x] New algorithm
- [ ] Update to an existing algorithm
- [ ] Error
- [ ] Proposal to the Repository

**Details:**

Add solution for LeetCode problem 3: Longest Substring without Repetition of Characters

P.S. I would like to work on it

**Comment by SnehhaPadmanabhan** [comment]
I would like to work on this if it's still available @nikochiko

**Comment by nikochiko** [comment]
Hey @SnehhaPadmanabhan thanks for your interest, but I have already opened a PR, please take up some other issue. Thanks!
