### ISSUE TITLE
Implementation of Project Euler Problem #201 Subsets with Unique Sum

### ISSUE THREAD

**Issue by srimani-programmer** [OpenGenus/cosmos#4379]
**This is a(n):**

- [x] New algorithm
- [ ] Update to an existing algorithm
- [ ] Error
- [x] Proposal to the Repository

**Details:**

**Comment by gunjanmimo** [comment]
I WANT TO TAKE THIS ISSUE @srimani-programmer

**Comment by Shishukumar74** [comment]
I am ready to solve this problem.
