### ISSUE TITLE
Shortest job first(preemptive),and priority scheduling (preemptive and non preemptive) in scheduling algorithms(operating system)- C.

### ISSUE THREAD

**Issue by MdAkdas** [OpenGenus/cosmos#4413]
**This is a(n):**

- [x ] New algorithm
- [ ] Update to an existing algorithm
- [ ] Error
- [ ] Proposal to the Repository

**Details:**

There are some scheduling algorithm in Operating system code. but these algorithm are not present.

**Comment by MdAkdas** [comment]
i would like to work on this issue. 
please assign me this. :)

**Comment by shwetachan** [comment]
i want to work on this issue . please assign me this issue.
I'll try my best :))

**Comment by Varshney200** [comment]
Please assign me this issue

**Comment by MdAkdas** [comment]
@arnavb please assign me this.
