### ISSUE TITLE
Auto Key Cipher in C, C++ and Java

### ISSUE THREAD

**Issue by ravireddy07** [OpenGenus/cosmos#4443]
**This is a(n):**

- [x] New algorithm
- [x] Update to an existing algorithm
- [ ] Error
- [x] Proposal to the Repository

**Details:**

 Implementation of this algorithm will done in C, C++ an Java. Please assign this to me  @AdiChat

**Comment by anshu18107** [comment]
I can work on the python part @ravireddy07 @AdiChat

**Comment by arnavb** [comment]
@anshu18107 Go ahead!

**Comment by ravireddy07** [comment]
Actually program in python is already there..! That's why i didn't included.  @arnavb
