### ISSUE TITLE
Addition of solution to the problem Tax Slabs in java

### ISSUE THREAD

**Issue by raksha009** [OpenGenus/cosmos#4533]
**This is a(n):**

- [x] New algorithm
- [ ] Update to an existing algorithm
- [ ] Error
- [x] Proposal to the Repository

**Details:**

I want to add solution to codechef's feb cook-off 2020 "Tax Slabs" problem in java as a participant of Gssoc'20.
Plz assign me this issue.  @arnavb

**Comment by arnavb** [comment]
@raksha009 could you please link the PR that corresponded to this issue?

**Comment by raksha009** [comment]
Yes, sorry i'll do it right now.
