### ISSUE TITLE
KNN algorithm in C++

### ISSUE THREAD

**Issue by Aman-Codes** [OpenGenus/cosmos#4634]
**This is a(n):**

- [ ] New algorithm
- [x] Update to an existing algorithm
- [ ] Error
- [x] Proposal to the Repository

**Details:**

Adding KNN algorithm in C++

**Comment by syedareehaquasar** [comment]
PLEASE ASSIGN ME THIS ... @arnavb

**Comment by Aman-Codes** [comment]
I am a gssoc participant please assign me this issue.

**Comment by arnavb** [comment]
Since Aman created the issue, I've assigned it to him.
