### ISSUE TITLE
There are 2 OOP Patterns folders and they need to be combined

### ISSUE THREAD

**Issue by arnavb** [OpenGenus/cosmos#4655]
**This is a(n):**

- [ ] New algorithm
- [ ] Update to an existing algorithm
- [x] Error
- [ ] Proposal to the Repository

**Details:**

There are two folders that contain OOP patterns, `cosmos/code/design_pattern/src/OOP_patterns` and `cosmos/code/design_pattern/src/oop_patterns`. Since they both serve the same purpose, they need to be combined. If anyone is willing to do this, please comment below and I will assign this issue to you.

**Comment by ritish099** [comment]
I want to do this please assign it to me

**Comment by ritish099** [comment]
even after syncing multiple times my local repository is only showing OOP_patterns folder. But oop_patterns is not showing. but I can see that both the folders are present in GitHub cosmos code base. why is it so?

**Comment by ritish099** [comment]
even both the folders are present in my forked repository but not in my local repository. Why is it so?

**Comment by arnavb** [comment]
@ritish099 Are you on MacOS or Windows? I was experiencing the same issues and its because both our OSes are case-insensitive. You might have noticed this while running `git clone`.

**Comment by ritish099** [comment]
Yes, I noticed that. Can we just push a new branch in my forked repository and do the changes over there and then create a pull request of the modified branch. It might do the task as both the folders are present in web interface of my forked repository

**Comment by ritish099** [comment]
assign me the issue. I will do it as I explained above

**Comment by arnavb** [comment]
@ritish099 Have you made any progress on this issue?

**Comment by ritish099** [comment]
Sir @arnavb . I hope that the issue is now resolved. Now in my forked repository on GitHub only OOP is there [OOP](https://github.com/ritish099/cosmos/tree/OOP/code/design_pattern/src) and from there I created this pull request

**Comment by arnavb** [comment]
Closed in #4722
