### ISSUE TITLE
Utility folder can be combined with unclassified folder

### ISSUE THREAD

**Issue by arnavb** [OpenGenus/cosmos#4719]
**This is a(n):**

- [ ] New algorithm
- [x] Update to an existing algorithm
- [x] Error
- [ ] Proposal to the Repository

**Details:**

The [utility](https://github.com/OpenGenus/cosmos/tree/master/code/utility) folder currently only contains one algorithm and it seems that it can be moved to the [unclassified](https://github.com/OpenGenus/cosmos/tree/master/code/unclassified) folder. If anyone wants to do this, comment below and I will assign this issue to you.

**Comment by ritish099** [comment]
assign it to me @arnavb . and check out the OOP problem. I think that it is now resolved

**Comment by ritish099** [comment]
Sir @arnavb , Check it out. Hope that it is done

**Comment by arnavb** [comment]
Closed in #4758.
