### ISSUE TITLE
There is an extra circle sort folder that can be removed

### ISSUE THREAD

**Issue by arnavb** [OpenGenus/cosmos#4720]
**This is a(n):**

- [ ] New algorithm
- [ ] Update to an existing algorithm
- [x] Error
- [ ] Proposal to the Repository

**Details:**

This folder (https://github.com/OpenGenus/cosmos/tree/master/code/sorting/circle_sort)basically serves no purpose. The readme inside isn't really useful because there is already a readme with graphics for circle sort in the correct directory. Thus, this directory can be deleted.

If anyone wants to do this, comment below and I will assign it to you.

**Comment by abhu-A-J** [comment]
I'm interested under GSSoC'20

**Comment by ritish099** [comment]
@arnavb assign it to me

**Comment by arnavb** [comment]
@abhu-A-J Since you commented first I have assigned it to you.

**Comment by abhu-A-J** [comment]
> @abhu-A-J Since you commented first I have assigned it to you.

Thanks!

**Comment by arnavb** [comment]
Closed in #4776.
