### ISSUE TITLE
n queen problem in c

### ISSUE THREAD

**Issue by Ankit152** [OpenGenus/cosmos#4723]
**This is a(n):**

- [x] New algorithm
- [x] Update to an existing algorithm
- [ ] Error
- [x] Proposal to the Repository

**Details:**

Number of ways to place N chess queens on an N×N chessboard so that no two queens attack each other without using recursion and backtracking.

**Comment by Ankit152** [comment]
please assign this issue to me.

**Comment by arnavb** [comment]
@Ankit152 The C++ algorithms for this exist here: https://github.com/OpenGenus/cosmos/tree/master/code/backtracking/src/n_queen

**Comment by Ankit152** [comment]
ok then let me implement it in C.
