### ISSUE TITLE
Leetcode Solution #101 SYMMETRIC TREE 

### ISSUE THREAD

**Issue by avanisingh0105** [OpenGenus/cosmos#4745]
**This is a(n):**

- [x] New algorithm
- [ ] Update to an existing algorithm
- [ ] Error
- [x] Proposal to the Repository

**Details:**

Given a binary tree, check whether it is a mirror of itself (ie, symmetric around its center).

**Problem Link:**

[https://leetcode.com/problems/symmetric-tree/](url)

**Comment by avanisingh0105** [comment]
I want to add the solution. Assign me this problem in C++  @arnavb

**Comment by Salonii02** [comment]
I want to add the solution and contribute to this issue.
I am gssoc20 participant.
please assign me this problem @arnavb 
thank you.

**Comment by arnavb** [comment]
@Salonii02 Fine, as long as the programming language isn't C++, which is what @avanisingh0105 is working on.

**Comment by Salonii02** [comment]
sir,I would be better with c++, should I proceed to work on?

**Comment by arnavb** [comment]
@Salonii02 C++ is already done, since I merged @avanisingh0105's pull request. Pick a different language.
