### ISSUE TITLE
Brian Kernighan's Algorithm to count set bits in an integer. C/C++

### ISSUE THREAD

**Issue by MdAkdas** [OpenGenus/cosmos#4764]
**This is a(n):**

- [x] New algorithm
- [ ] Update to an existing algorithm
- [ ] Error
- [x] Proposal to the Repository

**Details:**

This algo is used to count the no of set bits in an integer in O(logn) time.

**Comment by MdAkdas** [comment]
@arnavb @AdiChat  assign me this.

**Comment by parjanyaacoder** [comment]
@arnavb I would like to solve this issue in Java language. Please assign this issue to me.
