### ISSUE TITLE
Language and Languages folder can be combined to Languages folder

### ISSUE THREAD

**Issue by arnavb** [OpenGenus/cosmos#4803]
**This is a(n):**

- [ ] New algorithm
- [x] Update to an existing algorithm
- [x] Error
- [x] Proposal to the Repository

**Details:**

Title. If anyone wants to contribute to this, comment below.

The folder are: https://github.com/OpenGenus/cosmos/tree/master/code/language

and: https://github.com/OpenGenus/cosmos/tree/master/code/languages

languages seems like a better folder name.

**Comment by rbjoshi1309** [comment]
I would like to work on this issue.

**Comment by khuang0312** [comment]
I have submitted a pull request that should resolve this issue.

**Comment by arnavb** [comment]
Closed in #4901.
