### ISSUE TITLE
Java file name and folder name not matching in convert number binary

### ISSUE THREAD

**Issue by rbjoshi1309** [OpenGenus/cosmos#4829]
**This is a(n):**

- [ ] New algorithm
- [ ] Update to an existing algorithm
- [ ] Error
- [x] Proposal to the Repository

**Details:**

Java file name and folder name not matching in following folder :
cosmos/code/bit_manipulation/src/convert_number_binary

**Comment by arnavb** [comment]
Closed in #4830.
