### ISSUE TITLE
Java and JS file names and folder name not matching in count set bits

### ISSUE THREAD

**Issue by rbjoshi1309** [OpenGenus/cosmos#4831]
**This is a(n):**

- [ ] New algorithm
- [ ] Update to an existing algorithm
- [ ] Error
- [x] Proposal to the Repository

**Details:**

Java and Javascript file names and folder name not matching in following folder :
cosmos/code/bit_manipulation/src/count_set_bits

**Comment by arnavb** [comment]
Fixed in #4833.
