### ISSUE TITLE
Python file name and folder name not matching in gaussian_naive_bayes

### ISSUE THREAD

**Issue by rbjoshi1309** [OpenGenus/cosmos#4860]
**This is a(n):**

- [ ] New algorithm
- [ ] Update to an existing algorithm
- [ ] Error
- [x] Proposal to the Repository

**Details:**

Python file name and folder name not matching in following folder :
cosmos/code/artificial_intelligence/src/gaussian_naive_bayes

**Comment by arnavb** [comment]
Closed in #4861
