### ISSUE TITLE
JS and ipynb file names and folder name not matching in linear_regression 

### ISSUE THREAD

**Issue by rbjoshi1309** [OpenGenus/cosmos#4862]
**This is a(n):**

- [ ] New algorithm
- [ ] Update to an existing algorithm
- [ ] Error
- [x] Proposal to the Repository

**Details:**

JS and ipynb file names and folder name not matching in following folder :
cosmos/code/artificial_intelligence/src/linear_regression

**Comment by arnavb** [comment]
Closed in #4863
