### ISSUE TITLE
JS and ipynb file names and folder name not matching in q_learning

### ISSUE THREAD

**Issue by rbjoshi1309** [OpenGenus/cosmos#4866]
**This is a(n):**

- [ ] New algorithm
- [ ] Update to an existing algorithm
- [ ] Error
- [x] Proposal to the Repository

**Details:**

JS and ipynb file names and folder name not matching in following folder :
cosmos/code/artificial_intelligence/src/q_learning

**Comment by arnavb** [comment]
Closed in #4867.
