### ISSUE TITLE
solution to codechef solution MATCHES in C++ and C

### ISSUE THREAD

**Issue by Ankit152** [OpenGenus/cosmos#4869]
**This is a(n):**

- [x] New algorithm
- [ ] Update to an existing algorithm
- [ ] Error
- [x] Proposal to the Repository

**Details:**

Chef's son Chefu found some matches in the kitchen and he immediately starting playing with them.

The first thing Chefu wanted to do was to calculate the result of his homework — the sum of A and B, and write it using matches. Help Chefu and tell him the number of matches needed to write the result.
Digits are formed using matches in the following way:

**Comment by Ankit152** [comment]
please assign this issue to me.

**Comment by hanzohasashi33** [comment]
Can I take up this issue ?

**Comment by Ankit152** [comment]
thank you for merging.
