### ISSUE TITLE
C++ file name and folder name not matching in algorithm_x

### ISSUE THREAD

**Issue by rbjoshi1309** [OpenGenus/cosmos#4905]
**This is a(n):**

- [ ] New algorithm
- [ ] Update to an existing algorithm
- [ ] Error
- [x] Proposal to the Repository

**Details:**

C++ file name and folder name not matching in following folder :
cosmos/code/backtracking/src/algorithm_x

**Comment by arnavb** [comment]
Closed in #4906.
