### ISSUE TITLE
Java file name and folder name not matching in crossword_puzzle

### ISSUE THREAD

**Issue by rbjoshi1309** [OpenGenus/cosmos#4907]
**This is a(n):**

- [ ] New algorithm
- [ ] Update to an existing algorithm
- [ ] Error
- [x] Proposal to the Repository

**Details:**

Java file name and folder name not matching in following folder :
cosmos/code/backtracking/src/crossword_puzzle

**Comment by arnavb** [comment]
Closed in #4908.
