### ISSUE TITLE
Python file name and folder name not matching in m_coloring_problem

### ISSUE THREAD

**Issue by rbjoshi1309** [OpenGenus/cosmos#4909]
**This is a(n):**

- [ ] New algorithm
- [ ] Update to an existing algorithm
- [ ] Error
- [x] Proposal to the Repository

**Details:**

Python file name and folder name not matching in following folder :
cosmos/code/backtracking/src/m_coloring_problem

**Comment by arnavb** [comment]
Closed in #4910
