### ISSUE TITLE
File names and folder name not matching in number_of_ways_in_maze

### ISSUE THREAD

**Issue by rbjoshi1309** [OpenGenus/cosmos#4958]
**This is a(n):**

- [ ] New algorithm
- [ ] Update to an existing algorithm
- [ ] Error
- [x] Proposal to the Repository

**Details:**

File names and folder name not matching in following folder :
cosmos/code/backtracking/src/number_of_ways_in_maze

**Comment by arnavb** [comment]
Closed in #4959
