### ISSUE TITLE
Folder name powerset not written in proper way and file names not matching

### ISSUE THREAD

**Issue by rbjoshi1309** [OpenGenus/cosmos#4962]
**This is a(n):**

- [ ] New algorithm
- [ ] Update to an existing algorithm
- [ ] Error
- [x] Proposal to the Repository

**Details:**

Folder name powerset not written in proper way in following folder : 
cosmos/code/backtracking/src
File names and folder name not matching in following folder :
cosmos/code/backtracking/src/power_set

**Comment by arnavb** [comment]
Closed in #4963
