### ISSUE TITLE
 File names and folder name not matching in maximum_xor_value

### ISSUE THREAD

**Issue by rbjoshi1309** [OpenGenus/cosmos#5005]
**This is a(n):**

- [ ] New algorithm
- [ ] Update to an existing algorithm
- [ ] Error
- [x] Proposal to the Repository

**Details:**

File names and folder name not matching in following folder :
cosmos/code/bit_manipulation/src/maximum_xor_value

**Comment by arnavb** [comment]
Closed in #5006.
