### ISSUE TITLE
Fix Linguist language stats for this repo

### ISSUE THREAD

**Issue by arnavb** [OpenGenus/cosmos#5049]
**This is a(n):**

- [ ] New algorithm
- [ ] Update to an existing algorithm
- [x] Error
- [x] Proposal to the Repository

**Details:**

Looking at the following image:

<img width="1016" alt="Screen Shot 2020-04-01 at 6 04 18 PM" src="https://user-images.githubusercontent.com/30810402/78191051-36d85700-7443-11ea-908b-e102ae86d1c9.png">

It would seem that Jupyter notebooks constitute the majority of the code in the codebase. Obviously this is not true (there are I think 11 notebooks in this repository). The nature of Jupyter notebooks is that they take up many lines of code. Unfortunately, this means that this project is incorrectly classified in terms of Linguist. 

Based on github/linguist#3316, it seems the solution is to mark the Jupyter Notebook files as either vendored or documentation in the `.gitattributes` file (or to mark them for a specific language, although I doubt this is a good idea because then stats for that language will be skewed).

If anyone wants to do this, comment below.

**Comment by dapetillo** [comment]
Hi! It's my first time contributing in an open source project. I would like to take this good first issue!

I read the mentioned issue. Now, I could not find any `.gitattributes` file in the repository. If there is not, I was thinking to put it in `.git/`. If you think that it should be placed in some sub-folder, please let me know where, thank you!

**Comment by arnavb** [comment]
@dapetillo It needs to be placed in the root folder.

**Comment by arnavb** [comment]
Closed in #5208.
