### ISSUE TITLE
File names and folder name not matching in cohen_sutherland_lineclip

### ISSUE THREAD

**Issue by rbjoshi1309** [OpenGenus/cosmos#5090]
**This is a(n):**

- [ ] New algorithm
- [ ] Update to an existing algorithm
- [ ] Error
- [x] Proposal to the Repository

**Details:**

File names and folder name not matching in following folder :
cosmos/code/computational_geometry/src/cohen_sutherland_lineclip

**Comment by arnavb** [comment]
Closed in #5091
