### ISSUE TITLE
File names and folder name not matching in sutherland_hodgeman_clipping

### ISSUE THREAD

**Issue by rbjoshi1309** [OpenGenus/cosmos#5100]
**This is a(n):**

- [ ] New algorithm
- [ ] Update to an existing algorithm
- [ ] Error
- [x] Proposal to the Repository

**Details:**

File names and folder name not matching in following folder :
cosmos/code/computational_geometry/src/sutherland_hodgeman_clipping

**Comment by arnavb** [comment]
Closed in #5101.
