### ISSUE TITLE
 Folder name not written in proper way in quickhull

### ISSUE THREAD

**Issue by rbjoshi1309** [OpenGenus/cosmos#5102]
**This is a(n):**

- [ ] New algorithm
- [ ] Update to an existing algorithm
- [ ] Error
- [x] Proposal to the Repository

**Details:**

Folder name not written in proper way in following folder :
cosmos/code/computational_geometry/src/quickhull
File names and folder name not matching in following folder :
cosmos/code/computational_geometry/src/quick_hull

**Comment by arnavb** [comment]
Closed in #5103
