### ISSUE TITLE
Add Flood Fill in Computer Graphics

### ISSUE THREAD

**Issue by irakli** [OpenGenus/cosmos#5847]
**This is a(n):**

- [x] New algorithm
- [ ] Update to an existing algorithm
- [ ] Error
- [ ] Proposal to the Repository

**Details:**
Flood fill, also called seed fill, is an algorithm that determines the area connected to a given node in a multi-dimensional array

The flood-fill algorithm takes three parameters: a start node, a target color, and a replacement color. The algorithm looks for all nodes in the array that are connected to the start node by a path of the target color and changes them to the replacement color.

**Comment by HariniJeyaraman** [comment]
Can I work on this in C++ ? Would like to work on this for hacktoberfest 2020

**Comment by Kripa8702** [comment]
May I work on this in C++ @irakli ?
