### ISSUE TITLE
Cloning error on case-insensitive filesystems

### ISSUE THREAD

**Issue by aryanrawlani28** [OpenGenus/cosmos#5891]
**This is a(n):**

- [ ] New algorithm
- [ ] Update to an existing algorithm
- [x] Error
- [ ] Proposal to the Repository

**Details:**

Hello.
I'm currently on a Windows platform, which is a case-insensitive filesystem. Upon cloning the repository, it gives me the below log:

```
$ git clone https://github.com/OpenGenus/cosmos.git
Cloning into 'cosmos'...
remote: Enumerating objects: 12, done.
remote: Counting objects: 100% (12/12), done.
remote: Compressing objects: 100% (11/11), done.
remote: Total 64060 (delta 2), reused 2 (delta 0), pack-reused 64048
Receiving objects: 100% (64060/64060), 44.60 MiB | 988.00 KiB/s, done.
Resolving deltas: 100% (36899/36899), done.
Updating files: 100% (3742/3742), done.
warning: the following paths have collided (e.g. case-sensitive paths
on a case-insensitive filesystem) and only one from the same
colliding group is in the working tree:

  'code/dynamic_programming/src/longest_common_substring/Longest_Common_Substring.cpp'
  'code/dynamic_programming/src/longest_common_substring/longest_common_substring.cpp'
  'scripts/metadata/code/design_pattern/src/OOP_patterns/data.json'
  'scripts/metadata/code/design_pattern/src/oop_patterns/data.json'
```

This is because these files are the same name, just capitalization is different. Thus, 
- `scripts/metadata/code/design_pattern/src/oop_patterns/data.json` needs to be deleted - because another `OOP_patterns` folder exists.
- `code/dynamic_programming/src/longest_common_substring/longest_common_substring.cpp` needs to be renamed, because one solution already exists.

PR https://github.com/OpenGenus/cosmos/pull/5890 tries to fix this.

**Comment by AdiChat** [comment]
Nice work on identifying and fixing the issue 👍 

It is important to make things work across all different environments.

**Comment by Haricharan0310** [comment]
Hey @aryanrawlani28 @AdiChat  I was wondering if this issue is open? If it is, I would like to Contribute to it and could you please guide me on this?

**Comment by beef-erikson** [comment]
Just now noticed this was a closed issue. Followed the link from Octoberfest. Disregard my pull request; I shall look into current bugs!

Thanks!
