### ISSUE TITLE
Add Sparse Table Data Structure in C++

### ISSUE THREAD

**Issue by oyar99** [OpenGenus/cosmos#5958]
**This is a(n):**

- [x] New algorithm
- [ ] Update to an existing algorithm
- [ ] Error
- [ ] Proposal to the Repository

**Details:**

A sparse table is a data structure that can answer range queries.

**Comment by JhonRayoCoder** [comment]
I would like to work on this

**Comment by AdiChat** [comment]
Sure, you may get started with it and open a pull request for review 👍
