### ISSUE TITLE
Implement bit inversion in Rust language 

### ISSUE THREAD

**Issue by danwolb02** [OpenGenus/cosmos#5989]
**This is a(n):**

- [x] New algorithm
- [ ] Update to an existing algorithm
- [ ] Error
- [ ] Proposal to the Repository

**Details:**
Implement bit inversion in the Rust programming language.

**Comment by sourabhsingh282** [comment]
I would like to work on this

**Comment by danwolb02** [comment]
I am sorry @sourabhsingh282, I should have probably made this more clear. I already implemented this in #5990. But it would be very nice if you can review that.
