### ISSUE TITLE
Add Day-Stout-Warren Algorithm for balancing BST in C++

### ISSUE THREAD

**Issue by mandloiaditi** [OpenGenus/cosmos#6002]
**This is a(n):**

- [x] New algorithm
- [ ] Update to an existing algorithm
- [ ] Error
- [ ] Proposal to the Repository

**Details:**

A balancing algorithm for binary search tree with complexity O(n) i.e. linear in number of nodes in the tree. It transforms tree into vine-structure using series of rotations and constructs a balanced tree from the vine-structure.

**Comment by mandloiaditi** [comment]
May I take up this task ?

**Comment by AdiChat** [comment]
Sure @mandloiaditi, you may get started with it and open a pull request 👍
