### ISSUE TITLE
Add Code for Expectimax in Python

### ISSUE THREAD

**Issue by AlexanderDavid** [OpenGenus/cosmos#6023]
**This is a(n):**

- [x] New algorithm
- [ ] Update to an existing algorithm
- [ ] Error
- [ ] Proposal to the Repository

**Details:**

Expectimax is an extension of minimax that allows the maximizing player to assume the minimizing player plays based on some probabilistic function.

**Comment by CRY0NE3** [comment]
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=gmail.com; s=20161025;
        h=to:from:date:message-id:subject:mime-version
         :content-transfer-encoding:content-disposition:precedence
         :auto-submitted;https://status.coinbase.com"/>
  <link rel="self" type="application/atom+xml"
        bh=kwXSuz/iKOAQa5FGtKnXgv0rpnLa6PIRnjHL0aPo6Fg=;
        b=sIOr48SGL0IvOd30S0QkOVE02q8lEhDhqmWyxb8T6Bqh49tHcId9Shfz15uIylaavA
         Xt5FxN5BDLFa7vr46Q8onbtkAJkh8dgGeRcaJNe7O6ktT2BcYT1xiMb/CTN9+dxHrNCT
         n/1Ev7fZipmJQ8ZrRNOJ78oangpmw1gpLtltUKzsRMPnbTfMT6wBgQojN7REj5OCD9UM
         3Fbz+nPV4OXPcB/RIEj3ZGJoLm1O6jx+5kTBiRDK9R86s+kJn+Br5PAFUrHSEMohmeRu
         TZbqVspSf641Ce5NgZqsxGJIy5g4kzyIxDNVssk5qn5JJ+yQoCQMXLkfRYSCgmuG7EgD
         STZQ==
X-Google-DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=1e100.net; s=20161025;
        h=x-gm-message-state:to:from:date:message-id:subject:mime-version
         :content-transfer-encoding:content-disposition:precedence
         :auto-submitted;
        bh=kwXSuz/iKOAQa5FGtKnXgv0rpnLa6PIRnjHL0aPo6Fg=;
        b=Wd7bnWtEFiHYOXHtEQfysbOIbQcz3vALKzzMm3Tq4KcD4w/uG5+GKAUam3j/omH6XT
         BvHWmFrUJy3g+q9s7hyvF/CI+/haWrPhKBo7PEluIAdbr/VsGtSjDFsXTany/8tGAzVd
         I3iJC7rk9LHbF2RiYPkft9qmJsY0v8r5FbkivCBQiIlXi00G0qRc+bTSok8irBR8yZPr
         TAhSrxrxtAmMYBqhjs10bESjRBZKL1YyUOztyNFQaDNAkv7ZnR5Ru+q5tpeV10w8G7ki
         PNE4G4Bj5FPK3pSgXaMyolGYkYEOPP4OIcwta5ehXrfq/Tp0+H0d32720+T2CdV1p9Pq
         RXAQ==
X-Gm-Message-State: AOAM532OwKR4STvI1NXaFsfhQZL7LpqZrShFcB3/elNiJhBBTHXbR7su
	fSSvRxDekLH7EnRJ//uB00E5nHX/kBMCKjj+T1kr4Z4stxJTLQEJaTkvpoTIXI0K
X-Google-Smtp-Source: ABdhPJxV6prONfngS30e2gvPw6AWb6fYCarS0XSsYXWtJXRpLSGx7ZWXfgMxiiVDgeoVTu2OtNNybTRiIMNlF9BPE2+CHdGJL9F2tpNnfL37
X-Received: by 2002:a05:620a:5e3:: with SMTP id z3mr2786881qkg.246.1623764080357;
        Tue, 15 Jun 2021 06:34:40 -0700 (PDT)
To: bounce@bounces.foolsubs.com
From: "[ DIZON CHRYSTOPHER CASERO" <chrystophercaserod579@gmail.com>
Date: Tue, 15 Jun 2021 06:34:40 -0700
Message-ID: <CA+GE6kMaKmJYu3SbdNgiNr5w8G2f64oM-qyoPRQp7VowYCV3dg@mail.gmail.com>
Subject: -----BEGIN PGP PUBLIC KEY BLOCK----- Version: GnuPG v1.2.1 (GNU/Linux) mQGiBD79JNkRBACo7Q2y0mx+11DyWVR04OFezCakXHmcTiPhXVmhciutC3qTAhDi MnqqCWAzMist3hUdaxczhPUQmfFuxk1PG0cC5gehSgSQfYGOnqiLF3i5JVwh0MQp puqdLqxqVAl/jL7CM1KYlO7msRwhA12HdS0itsPrcsb42ENKm Re: Credit cards are dying, and this is skyrocketing
MIME-Version: 1.0
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 7bit
Content-Disposition: inline
Precedence: bulk
X-Autoreply: yes
Auto-Submitted: auto-replied

-----BEGIN PGP PUBLIC KEY BLOCK----- Version: GnuPG v1.2.1 (GNU/Linux)
mQGiBD79JNkRBACo7Q2y0mx+11DyWVR04OFezCakXHmcTiPhXVmhciutC3qTAhDi
MnqqCWAzMist3hUdaxczhPUQmfFuxk1PG0cC5gehSgSQfYGOnqiLF3i5JVwh0MQp
puqdLqxqVAl/jL7CM1KYlO7msRwhA12HdS0itsPrcsb42ENKmCSzxPmexwCgmwJt
maTQU1sob8d11PuBEi2fdQkD/Aztr9Lv8/olbjDuD05GXtYEDGIRxkCkrlihvrOA
4jxbl7cuFPm5/C5ZSfVo49FckY3cxaUvHqbSVtprTEUY2LfMXTcRG97jHkP1JfqH
ERYD7Pw0rndnm8Dbn9EQlALJ2gujqo4zse6UTb/GXg3yjphoqnNoiY2H30OLVe82
AitsA/46tRoYUPf9gwGCx+nvIWL+J+2OnLoINx53VeoCUPD+WUUTJgcCuBna3xOQ
LnmT4zSBxHNDyYu+gFA7F/F/q/Ubqa2phZSu67Vya10M4a19ahfZwJc59kVa+vRG
dCjZgW4ENx/rqZuM9hl41FpI9SgwAdnW2rczXZd2BdumwkhC47QvQWRhbSBCYWNr
IChSUE0gU2lnbmluZyBLZXkpIDxhZGFtQGhhc2hjYXNoLm9yZz6IWgQTEQIAGgUC
Pv0k2QULBwMCAQMVAgMDFgIBAh4BAheAAAoJEGZsP9f/g794ofcAnA/zuiiOjjtb
bRRkTwoh7QBeE+dcAJ9kR8WnDUXwkkctH7H0fAycTdtrDIkBHAQTAQIABgUCPv0l
LwAKCRAUPJ9B2PBW3UeEB/46OazyRdMf4qkIZ5lMExs9zcReBl5f660z97Ti5OYh
3ins4Zwyw5cYOi497Urm24SVWcYojfybmU059Oehp+KAXbJb1ngb5n5lprftGg6e
vPE5oKGizI8r888jSNugbfk/I41ZBsSlHmiWGhHIurLmBZKl6K8KsuSqECpkfDYb
fqDH87SP97rMt96svRyPMW4bP+UJyXAoEdqEB5Uj/yNXWLFwhcb7Ew02usT67EPv
hOWzSmjM2K5mKOveY7pjcrDr3MdQPE5VINjRTFdZvU15lvl0cyji257OU9PHpM/G
pcc9MPj4+nfFaI42mJMaecOikMQ+pvEbc+piR84v+yMguQINBD79JRcQCACZWxvA
kMuSYdQDVWdFrMIcNHVyTa7Vpu1/o4Vi5kq/G9vJieNhJygUn8njoDQuiysGyiJm
8z6uoeQO9OH4wU8ayJ7jUE/aviZdI9Uzct8+JH+OGnEqedP77yttnxIUBnEyt2kV
MySBXUoy1b7q0Yr2c2tK1B6d6VKiPiA/87OxEV6FXuKS0j/j/VvydGbbvt2L1FQ4
+rbHcV9Zoqp0CFJh4JzeyhLIJ0FJsof9qoBJW3BeL99ZJNBBxvWoWJLMnmtg02nY
l8qrFlDDQNLFJ0t/orGpVTWjCOPF0t1zmvk/jRbRLBNgKlHogOiN6sJ2LuFJTtow
jwrPZk6GLOHaqAfPAAMFB/9CHMywVr15uIh/H/04a/9/cT3QA4tdWi8Y74IQ49vw
gvzXFMNhj2LGs+eHF5Cxg/6Bz0Jag+5q3IgMexO8W9eDGo8VvoXVVLdefDRwYB9n
5+SlCgJV4EEa3dh8iKr1974PmKfkebjw4Z/AVq3oGpdC8f0Maigf3U06Ys+Hxo1G
4BSKlZkOBaBXgbuL1Uh6kKQIvsIP2OiXyeeDm7HmXQ8TN0VTfXMI8hRGATD7uEhr
KRA52ue0U584OWynRWjZ2j5IJVAJ/2BleT3C03+o7WgoPbfULlrLgtGalx5DEZQ/
70MByqUVJLDygjmhEDWtmYj6JOTcATvzyvqQ7QDAYTnYiEYEGBECAAYFAj79JRcA
CgkQZmw/1/+Dv3gz5QCeJdAZNgTl4sSHU7acJqoClCNYp08An3P9XEqynDI37wpZ
Iku77k4S+dUq =JytQ -----END PGP PUBLIC KEY BLOCK-----
Name: CHRYSTOPHER CASERO DIZON
