### ISSUE TITLE
fix broken images links in packetsniffer README

### ISSUE THREAD

**Issue by walidbarakat** [OpenGenus/cosmos#6129]
**This is a(n):**

- [ ] New algorithm
- [ ] Update to an existing algorithm
- [x] Error
- [ ] Proposal to the Repository

**Details:**

this issue to fix the broken link in [packetsniffer README](https://github.com/OpenGenus/cosmos/tree/master/code/networking/src/packetsniffer)

**Comment by bindu-r02** [comment]
May I work on it

**Comment by bindu-r02** [comment]
Submitted pull request #6131
