### ISSUE TITLE
Greedy Algorithm, Split Array Largest Sum

### ISSUE THREAD

**Issue by parvsharmaa** [OpenGenus/cosmos#6132]
**This is a(n):**

- [x] New algorithm
- [x] Proposal to the Repository

**Details:**

I **would like to add a greedy algorithm for Split Array Largest Sum** which will include Problem Statement along with the examples, Constraints and Complexity Analysis with the Optimized Solution.

#hacktoberfest2021

**Comment by parvsharmaa** [comment]
@AdiChat can i proceed with this issue ?

**Comment by AdiChat** [comment]
@parvsharmaa Sure, you may work on it and open a pull request

**Comment by parvsharmaa** [comment]
@AdiChat done with the Issue, please review pr #6141

**Comment by coding-sourabh** [comment]
@AdiChat  I would like to work on it

**Comment by parvsharmaa** [comment]
@coding-sourabh this issue has already been completed, u may proceed with the incompleted once, with permission of @AdiChat
