### ISSUE TITLE
Maximum Subarray

### ISSUE THREAD

**Issue by Op-panda** [OpenGenus/cosmos#6212]
**This is a:**

- [x] New algorithm
- [ ] Update to an existing algorithm
- [ ] Error
- [ ] Proposal to the Repository

**Details:**

Given an integer array nums, find the contiguous subarray (containing at least one number) which has the largest sum and return its sum.

A subarray is a contiguous part of an array.

**Comment by DavidMaged171** [comment]
Could you assign me to this problem I can solve it using c++
