### ISSUE TITLE
Rotate image

### ISSUE THREAD

**Issue by Op-panda** [OpenGenus/cosmos#6213]
**This is a:**

- [x] New algorithm 
- [ ] Update to an existing algorithm
- [ ] Error
- [ ] Proposal to the Repository

**Details:**

You are given an n x n 2D matrix representing an image, rotate the image by 90 degrees (clockwise).

You have to rotate the image in-place, which means you have to modify the input 2D matrix directly. DO NOT allocate another 2D matrix and do the rotation.

A subarray is a contiguous part of an array.

**Comment by AdithyaS99** [comment]
Please assign this to me. I would like to contribute
