### ISSUE TITLE
[Hacktoberfest] Implementing Fibonacci with Java

### ISSUE THREAD

**Issue by lyfer233** [OpenGenus/cosmos#6229]
**This is a(n):**

- [ ] New algorithm
- [x] Update to an existing algorithm
- [ ] Error
- [ ] Proposal to the Repository

**Details:**

Using Java to implemente Fibonacci.

**Comment by nishajha629** [comment]
can you please  assign me this issue

**Comment by rich5k** [comment]
Please I am a newbie. Can this issue be assigned to me?

**Comment by lyfer233** [comment]
#6230 I had finished this task.
