### ISSUE TITLE
GCD related problems

### ISSUE THREAD

**Issue by lyfer233** [OpenGenus/cosmos#6234]
**This is a(n):**

- [x] New algorithm
- [ ] Update to an existing algorithm
- [ ] Error
- [ ] Proposal to the Repository

**Details:**

Given an array nums of positive integers. Your task is to select some subset of nums, multiply each element by an integer and add all these numbers. The array is said to be good if you can obtain a sum of 1 from the array by any possible subset and multiplicand.
Return True if the array is good otherwise return False.

(I think it should grouped into number theory

**Comment by lyfer233** [comment]
> Can I also work on GCD related problems?

OK~ 😄

**Comment by sreelakshmig009** [comment]
@lyfer233 Can you assign me to it?

**Comment by Devolious** [comment]
@AdiChat Can I work on GCD-related problems? Please assign it to me.
