### ISSUE TITLE
Python sum of digits algorithm is throwing an error

### ISSUE THREAD

**Issue by joaopedrocampos** [OpenGenus/cosmos#6259]
**This is a(n):**

- [ ] New algorithm
- [ ] Update to an existing algorithm
- [x] Error
- [ ] Proposal to the Repository

**Details:**
The `sum_of_digits.py` algorithm is throwing an error since it is using the wronk variable to calculate the sum.

It should use the variable `input_text` but it is trying to use `input_number`.

**Comment by vacom13** [comment]
@joaopedrocampos okay great!

**Comment by joaopedrocampos** [comment]
I'm closing the issue since the fix was merged
