### ISSUE TITLE
Clean easy to understand C++ code for counting sort.

### ISSUE THREAD

**Issue by Ankit152** [OpenGenus/cosmos#6363]
**This is a(n):**

- [ ] New algorithm
- [x] Update to an existing algorithm
- [ ] Error
- [x] Proposal to the Repository

**Details:**

The existing code of counting sort in CPP is **not very clean**. I will be grateful if I am assigned the task of writing cleaner code for counting sort in CPP with proper comments. It will be much easier to understand.

**Comment by harshit078** [comment]
Can you assign the task to me? I can write the code

**Comment by BrookeScoglio** [comment]
Hi, can you assign me this task? I am a first-time contributor and would love to work on this!
