### ISSUE TITLE
Implementing Topological Sort in JS

### ISSUE THREAD

**Issue by AlphaVS-76** [OpenGenus/cosmos#6470]
**This is a(n):**

- [ ] New algorithm
- [x] Update to an existing algorithm
- [ ] Error
- [ ] Proposal to the Repository

**Details:**

- JavaScript implementation is required for many algorithm, I started with this.
- links PR #6469

**Comment by AlphaVS-76** [comment]
I think the label should be Hacktoberfest-accepted 😃

**Comment by 12-malak** [comment]
@AdiChat @AlphaVS-76 Hi, I would like to work on this issue. Please assign me.
