### ISSUE TITLE
Dinic's algorithm 

### ISSUE THREAD

**Issue by vedant-z** [OpenGenus/cosmos#6505]
**This is a(n):**

- [x] New algorithm
- [ ] Update to an existing algorithm
- [ ] Error
- [x] Proposal to the Repository

**Details:**
Dinic's algorithm is used to solve maximum flow questions

A matching in a graph is a set of edges that does not have common vertices (i.e., no two edges share a common vertex). A matching is called a maximum matching if it contains the largest possible number of edges matching as many vertices as possible.

**Comment by vedant-z** [comment]
@AdiChat Please assign this issue to me

**Comment by vedant-z** [comment]
@AdiChat I want to add new algorithm

**Comment by imNilabja** [comment]
I would like to do this task ,can you assign me.
