### ISSUE TITLE
Number of Islands using DFS [Hacktoberfest]

### ISSUE THREAD

**Issue by harshagrawal523** [OpenGenus/cosmos#6509]
**This is a(n):**

- [x] New algorithm
- [ ] Update to an existing algorithm
- [ ] Error
- [ ] Proposal to the Repository

**Details:**
Given an m x n 2D binary grid grid which represents a map of '1's (land) and '0's (water), return the number of islands.

An island is surrounded by water and is formed by connecting adjacent lands horizontally or vertically. You may assume all four edges of the grid are all surrounded by water.

**Comment by harshagrawal523** [comment]
@AdiChat Please accept the issue with hacktober tag and review my [PR](https://github.com/OpenGenus/cosmos/pull/6510) here

**Comment by suprity04** [comment]
Hey @OpenGenus I want to add an efficient approach to your problem. Can you please assign this to me.
