### ISSUE TITLE
Euler Phi Sieve

### ISSUE THREAD

**Issue by krnbatra** [OpenGenus/cosmos#665]
Can I add implementation of Euler Phi Sieve in C++?

**Comment by AdiChat** [comment]
Sure. Go for it 👍

**Comment by krnbatra** [comment]
Added Euler Phi Sieve. #670

**Comment by ansonb** [comment]
I would like to implement this in python

**Comment by AdiChat** [comment]
Sure @ansonb Go for it 👍

**Comment by ansonb** [comment]
kindly review the python implementation #1497
