### ISSUE TITLE
Insertion Sort Dart

### ISSUE THREAD

**Issue by kwe92** [OpenGenus/cosmos#6698]
**This is a(n):**

- [X ] New algorithm
- [ ] Update to an existing algorithm
- [ ] Error
- [ ] Proposal to the Repository

**Details:**

I am adding Insertion Sort

**Comment by kwe92** [comment]
Adding insertion sort dart

**Comment by prokaushik** [comment]
I am capable of handling this effectively. Kindly assign me this particular issue.
