### ISSUE TITLE
Red-black Tree

### ISSUE THREAD

**Issue by ThanasisGkanos** [OpenGenus/cosmos#672]
Basically, a self-balancing binary tree: [https://en.wikipedia.org/wiki/Red%E2%80%93black_tree](url)

I can do the Java implementation :)

**Comment by AdiChat** [comment]
Sure. Go for it 👍

**Comment by RajatGarg97** [comment]
Can I try to implement this in C++ ? @AdiChat

**Comment by AdiChat** [comment]
Sure @RajatGarg97 Go for it 👍

**Comment by JonNRb** [comment]
I have a pure C implementation that works like a min-heap and has push and pop functions. I wouldn't mind contributing it.
