### ISSUE TITLE
Job Sequencing Problem in Java

### ISSUE THREAD

**Issue by ARCHITABHATTAD** [OpenGenus/cosmos#6729]
This is a(n):
- [ ] New algorithm
- [x] Update to an existing algorithm
- [ ] Error
- [ ] Proposal to the Repository

**Details:**
Wanting to add the Job Sequencing Problem in Java

**Comment by ARCHITABHATTAD** [comment]
@AdiChat Please accept the issue with hacktober tag and review my PR here

**Comment by akash47angadi** [comment]
@AdiChat Please accept my PR

**Comment by ARCHITABHATTAD** [comment]
@akash47angadi and @shub2003 This issue was raised by me , if you want to contribute you can raise another issue and raise a PR there.

**Comment by ARCHITABHATTAD** [comment]
@AdiChat I have raised a PR and request you accept it under Hacktoberfest 2023
