### ISSUE TITLE
Add code in multiple languages for existing algorithms

### ISSUE THREAD

**Issue by Zish303** [OpenGenus/cosmos#6752]
**This is a(n):**
- [ ] New algorithm
- [X] Update to an existing algorithm
- [ ] Error
- [ ] Proposal to the Repository

**Details:**

Various backtracking algorithms (crossword_puzzle, generate_parentheses, kth_grammar, m_coloring_problem, etc) are only available in a single language.
I want to add Code for these algorithms in other languages (C, C++, Python, Java, Javascript, Go) also.
I will add Code for all algorithms in the "backtracking" directory.

Please assign this to me and also add the "Hacktoberfest" label.

**Comment by Shubh2003** [comment]
@AdiChat can you please this pull request and merge it
