### ISSUE TITLE
2d line segment intersection algorithm

### ISSUE THREAD

**Issue by ivanrein** [OpenGenus/cosmos#689]
I'll implement this in c++

**Comment by AdiChat** [comment]
Sure. Go for it 👍

**Comment by ivanrein** [comment]
I've [added it](https://github.com/OpenGenus/cosmos/pull/772)

**Comment by ivanrein** [comment]
sorry, there was a mistake, I forgot to copy my code after writing it on my IDE. please [see my new pull request], it'll write over my old one (https://github.com/OpenGenus/cosmos/pull/776)

**Comment by AdiChat** [comment]
No problem. Merged 👍
